'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/routes/talks/Blog.svelte generated by Svelte v3.24.0 */

const css = {
	code: "h2{margin-top:2rem}pre{background:#eee;padding:1rem;border-radius:1rem}blockquote{margin:0;background:#ddd;padding:3px 1.5rem 3px 3rem;position:relative;border-radius:1rem}blockquote:after{content:'>';color:#aaa;font-size:30px;position:absolute;top:33%;left:1rem}blockquote p{padding:0}",
	map: "{\"version\":3,\"file\":\"Blog.svelte\",\"sources\":[\"Blog.svelte\"],\"sourcesContent\":[\"<script>\\nexport let data; // data is mainly being populated from the /plugins/edlerjs-plugin-markdown/index.js\\n</script>\\n\\n<style>\\nh1 {\\n  margin-bottom: 10px;\\n}\\n\\n.title {\\n  margin-top: 1rem;\\n  margin-bottom: 1rem;\\n  padding-bottom: 1rem;\\n  border-bottom: 1px solid #ddd;\\n}\\n\\n:global(h2) {\\n  margin-top: 2rem;\\n}\\n\\n:global(pre) {\\n  background: #eee;\\n  padding: 1rem;\\n  border-radius: 1rem;\\n}\\n\\n:global(blockquote) {\\n  margin: 0;\\n  background: #ddd;\\n  padding: 3px 1.5rem 3px 3rem;\\n  position: relative;\\n  border-radius: 1rem;\\n}\\n:global(blockquote:after) {\\n  content: '>';\\n  color: #aaa;\\n  font-size: 30px;\\n  position: absolute;\\n  top: 33%;\\n  left: 1rem;\\n}\\n\\n:global(blockquote p) {\\n  padding: 0;\\n}</style>\\n\"],\"names\":[],\"mappings\":\"AAgBQ,EAAE,AAAE,CAAC,AACX,UAAU,CAAE,IAAI,AAClB,CAAC,AAEO,GAAG,AAAE,CAAC,AACZ,UAAU,CAAE,IAAI,CAChB,OAAO,CAAE,IAAI,CACb,aAAa,CAAE,IAAI,AACrB,CAAC,AAEO,UAAU,AAAE,CAAC,AACnB,MAAM,CAAE,CAAC,CACT,UAAU,CAAE,IAAI,CAChB,OAAO,CAAE,GAAG,CAAC,MAAM,CAAC,GAAG,CAAC,IAAI,CAC5B,QAAQ,CAAE,QAAQ,CAClB,aAAa,CAAE,IAAI,AACrB,CAAC,AACO,gBAAgB,AAAE,CAAC,AACzB,OAAO,CAAE,GAAG,CACZ,KAAK,CAAE,IAAI,CACX,SAAS,CAAE,IAAI,CACf,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,GAAG,CACR,IAAI,CAAE,IAAI,AACZ,CAAC,AAEO,YAAY,AAAE,CAAC,AACrB,OAAO,CAAE,CAAC,AACZ,CAAC\"}"
};

const Blog = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { data } = $$props; // data is mainly being populated from the /plugins/edlerjs-plugin-markdown/index.js
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$result.css.add(css);
	return ``;
});

module.exports = Blog;
