'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/components/Button.svelte generated by Svelte v3.26.0 */

const css = {
	code: "a.svelte-4jl1zh{text-decoration:none;border:0;padding:12px 30px;background:#307f8b;color:white;font-size:18px;font-family:\"Inter\";border-radius:4px;cursor:pointer}.black.svelte-4jl1zh{background:#000000}a.svelte-4jl1zh:hover{background:#26636d}.black.svelte-4jl1zh:hover{background:#131313}",
	map: "{\"version\":3,\"file\":\"Button.svelte\",\"sources\":[\"Button.svelte\"],\"sourcesContent\":[\"<script>\\nexport let black;\\nexport let href;\\n</script>\\n\\n<style>\\na {\\n  text-decoration: none;\\n  border: 0;\\n  padding: 12px 30px;\\n  background: #307f8b;\\n  color: white;\\n  font-size: 18px;\\n  font-family: \\\"Inter\\\";\\n  border-radius: 4px;\\n  cursor: pointer;\\n}\\n.black {\\n  background: #000000;\\n}\\na:hover {\\n  background: #26636d;\\n}\\n.black:hover {\\n  background: #131313;\\n}</style>\\n\\n<a {href} rel=\\\"noreferrer\\\" target=\\\"_blank\\\" class:black>\\n  <slot />\\n</a>\\n\"],\"names\":[],\"mappings\":\"AAMA,CAAC,cAAC,CAAC,AACD,eAAe,CAAE,IAAI,CACrB,MAAM,CAAE,CAAC,CACT,OAAO,CAAE,IAAI,CAAC,IAAI,CAClB,UAAU,CAAE,OAAO,CACnB,KAAK,CAAE,KAAK,CACZ,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,OAAO,CACpB,aAAa,CAAE,GAAG,CAClB,MAAM,CAAE,OAAO,AACjB,CAAC,AACD,MAAM,cAAC,CAAC,AACN,UAAU,CAAE,OAAO,AACrB,CAAC,AACD,eAAC,MAAM,AAAC,CAAC,AACP,UAAU,CAAE,OAAO,AACrB,CAAC,AACD,oBAAM,MAAM,AAAC,CAAC,AACZ,UAAU,CAAE,OAAO,AACrB,CAAC\"}"
};

const Button = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { black } = $$props;
	let { href } = $$props;
	if ($$props.black === void 0 && $$bindings.black && black !== void 0) $$bindings.black(black);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	$$result.css.add(css);
	return `<a${add_attribute("href", href, 0)} rel="${"noreferrer"}" target="${"_blank"}" class="${["svelte-4jl1zh", black ? "black" : ""].join(" ").trim()}">${slots.default ? slots.default({}) : ``}</a>`;
});

module.exports = Button;
