'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/components/Card.svelte generated by Svelte v3.26.0 */

const css = {
	code: ".container.svelte-1nye1v9{padding:35px;background:#1c464d;display:grid;grid-gap:20px;place-items:start}.darkest.svelte-1nye1v9{background:#162b2e}.center.svelte-1nye1v9{margin:0 auto}",
	map: "{\"version\":3,\"file\":\"Card.svelte\",\"sources\":[\"Card.svelte\"],\"sourcesContent\":[\"<script>\\nexport let darkest, center;\\n</script>\\n\\n<style>\\n.container {\\n  padding: 35px;\\n  background: #1c464d;\\n  display: grid;\\n  grid-gap: 20px;\\n  place-items: start;\\n}\\n.darkest {\\n  background: #162b2e;\\n}\\n.center {\\n  margin: 0 auto;\\n}</style>\\n\\n<div class=\\\"container\\\" class:darkest class:center>\\n  <slot />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAKA,UAAU,eAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,UAAU,CAAE,OAAO,CACnB,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CACd,WAAW,CAAE,KAAK,AACpB,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,UAAU,CAAE,OAAO,AACrB,CAAC,AACD,OAAO,eAAC,CAAC,AACP,MAAM,CAAE,CAAC,CAAC,IAAI,AAChB,CAAC\"}"
};

const Card = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { darkest } = $$props, { center } = $$props;
	if ($$props.darkest === void 0 && $$bindings.darkest && darkest !== void 0) $$bindings.darkest(darkest);
	if ($$props.center === void 0 && $$bindings.center && center !== void 0) $$bindings.center(center);
	$$result.css.add(css);

	return `<div class="${[
		"container svelte-1nye1v9",
		(darkest ? "darkest" : "") + " " + (center ? "center" : "")
	].join(" ").trim()}">${slots.default ? slots.default({}) : ``}</div>`;
});

/* src/components/Button.svelte generated by Svelte v3.26.0 */

const css$1 = {
	code: "a.svelte-4jl1zh{text-decoration:none;border:0;padding:12px 30px;background:#307f8b;color:white;font-size:18px;font-family:\"Inter\";border-radius:4px;cursor:pointer}.black.svelte-4jl1zh{background:#000000}a.svelte-4jl1zh:hover{background:#26636d}.black.svelte-4jl1zh:hover{background:#131313}",
	map: "{\"version\":3,\"file\":\"Button.svelte\",\"sources\":[\"Button.svelte\"],\"sourcesContent\":[\"<script>\\nexport let black;\\nexport let href;\\n</script>\\n\\n<style>\\na {\\n  text-decoration: none;\\n  border: 0;\\n  padding: 12px 30px;\\n  background: #307f8b;\\n  color: white;\\n  font-size: 18px;\\n  font-family: \\\"Inter\\\";\\n  border-radius: 4px;\\n  cursor: pointer;\\n}\\n.black {\\n  background: #000000;\\n}\\na:hover {\\n  background: #26636d;\\n}\\n.black:hover {\\n  background: #131313;\\n}</style>\\n\\n<a {href} rel=\\\"noreferrer\\\" target=\\\"_blank\\\" class:black>\\n  <slot />\\n</a>\\n\"],\"names\":[],\"mappings\":\"AAMA,CAAC,cAAC,CAAC,AACD,eAAe,CAAE,IAAI,CACrB,MAAM,CAAE,CAAC,CACT,OAAO,CAAE,IAAI,CAAC,IAAI,CAClB,UAAU,CAAE,OAAO,CACnB,KAAK,CAAE,KAAK,CACZ,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,OAAO,CACpB,aAAa,CAAE,GAAG,CAClB,MAAM,CAAE,OAAO,AACjB,CAAC,AACD,MAAM,cAAC,CAAC,AACN,UAAU,CAAE,OAAO,AACrB,CAAC,AACD,eAAC,MAAM,AAAC,CAAC,AACP,UAAU,CAAE,OAAO,AACrB,CAAC,AACD,oBAAM,MAAM,AAAC,CAAC,AACZ,UAAU,CAAE,OAAO,AACrB,CAAC\"}"
};

const Button = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { black } = $$props;
	let { href } = $$props;
	if ($$props.black === void 0 && $$bindings.black && black !== void 0) $$bindings.black(black);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	$$result.css.add(css$1);
	return `<a${add_attribute("href", href, 0)} rel="${"noreferrer"}" target="${"_blank"}" class="${["svelte-4jl1zh", black ? "black" : ""].join(" ").trim()}">${slots.default ? slots.default({}) : ``}</a>`;
});

/* src/components/Sections/CallForPeople.svelte generated by Svelte v3.26.0 */

const css$2 = {
	code: ".background.svelte-1e9atp{--small-padding:var(--media-lte-sm) 0 0 220px 0;padding:var(--small-padding, 200px 40px 270px 40px);background:#2b636c;background-image:url(/images/forest.svg), url(/images/lake.svg);background-position:bottom left, top;background-repeat:repeat-x, no-repeat;--mobile-backgrounds:var(--media-lte-sm) auto 130px;background-size:var(--mobile-backgrounds, auto 150px);display:grid;justify-content:center}.container.svelte-1e9atp{display:grid;--small-grid:var(--media-lte-sm) 0;grid-gap:var(--small-grid, 30px);max-width:var(--container-width)}h3.svelte-1e9atp{font-size:28px;font-weight:normal}p.svelte-1e9atp{font-size:16px;--small-font-size:var(--media-lte-sm) 14px}h3.svelte-1e9atp,p.svelte-1e9atp{margin:0;--small-width:var(--media-lte-sm) 100%;width:var(--small-width, 90%);color:var(--sky-blue)}",
	map: "{\"version\":3,\"file\":\"CallForPeople.svelte\",\"sources\":[\"CallForPeople.svelte\"],\"sourcesContent\":[\"<script>\\nimport Card from '../Card.svelte';\\nimport Button from '../Button.svelte';\\n</script>\\n\\n<style>\\n.background {\\n  --small-padding: var(--media-lte-sm) 0 0 220px 0;\\n  padding: var(--small-padding, 200px 40px 270px 40px);\\n\\n  background: #2b636c;\\n  background-image: url(/images/forest.svg), url(/images/lake.svg);\\n  background-position: bottom left, top;\\n  background-repeat: repeat-x, no-repeat;\\n\\n  --mobile-backgrounds: var(--media-lte-sm) auto 130px;\\n  background-size: var(--mobile-backgrounds, auto 150px);\\n\\n  display: grid;\\n  justify-content: center;\\n}\\n.container {\\n  display: grid;\\n  --small-grid: var(--media-lte-sm) 0;\\n  grid-gap: var(--small-grid, 30px);\\n  max-width: var(--container-width);\\n}\\nh3 {\\n  font-size: 28px;\\n  font-weight: normal;\\n}\\np {\\n  font-size: 16px;\\n  --small-font-size: var(--media-lte-sm) 14px;\\n}\\nh3,\\np {\\n  margin: 0;\\n  --small-width: var(--media-lte-sm) 100%;\\n  width: var(--small-width, 90%);\\n  color: var(--sky-blue);\\n}</style>\\n\\n<div class=\\\"background\\\" id=\\\"cfp\\\">\\n  <div class=\\\"container\\\">\\n    <Card center>\\n      <h3>Call for initial proposals - Deadline September 18th!</h3>\\n      <p>\\n        If you're interested in doing a talk, the button below will bring you to the right place! First time doing a\\n        talk? No Problem! We welcome talks of all levels, from beginner to advanced, long and short. If you have more\\n        specific questions you can reach us on the <a\\n          rel=\\\"noreferrer\\\"\\n          target=\\\"_blank\\\"\\n          href=\\\"https://discord.gg/qzfM2JU\\\">\\n          Svelte discord server\\n        </a> .\\n      </p>\\n      <Button href=\\\"https://forms.gle/sGLyg5sLd4kKwRXZ6\\\">Send proposal</Button>\\n    </Card>\\n    <Card center darkest>\\n      <h3>Looking for sponsors</h3>\\n      <p>\\n        Since last time we've decided to try to bring the online experience to another level by improving the quality.\\n        If you (or your company) are interested in sponsoring the event, reach out to us via email using the link below\\n        and we can have a chat.\\n      </p>\\n      <Button href=\\\"mailto:sponsors@sveltesociety.dev\\\" black>Send email</Button>\\n    </Card>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAMA,WAAW,cAAC,CAAC,AACX,eAAe,CAAE,+BAA+B,CAChD,OAAO,CAAE,IAAI,eAAe,CAAC,sBAAsB,CAAC,CAEpD,UAAU,CAAE,OAAO,CACnB,gBAAgB,CAAE,IAAI,kBAAkB,CAAC,CAAC,CAAC,IAAI,gBAAgB,CAAC,CAChE,mBAAmB,CAAE,MAAM,CAAC,IAAI,CAAC,CAAC,GAAG,CACrC,iBAAiB,CAAE,QAAQ,CAAC,CAAC,SAAS,CAEtC,oBAAoB,CAAE,8BAA8B,CACpD,eAAe,CAAE,IAAI,oBAAoB,CAAC,WAAW,CAAC,CAEtD,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,MAAM,AACzB,CAAC,AACD,UAAU,cAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,YAAY,CAAE,qBAAqB,CACnC,QAAQ,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CACjC,SAAS,CAAE,IAAI,iBAAiB,CAAC,AACnC,CAAC,AACD,EAAE,cAAC,CAAC,AACF,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,MAAM,AACrB,CAAC,AACD,CAAC,cAAC,CAAC,AACD,SAAS,CAAE,IAAI,CACf,iBAAiB,CAAE,wBAAwB,AAC7C,CAAC,AACD,gBAAE,CACF,CAAC,cAAC,CAAC,AACD,MAAM,CAAE,CAAC,CACT,aAAa,CAAE,wBAAwB,CACvC,KAAK,CAAE,IAAI,aAAa,CAAC,IAAI,CAAC,CAC9B,KAAK,CAAE,IAAI,UAAU,CAAC,AACxB,CAAC\"}"
};

const CallForPeople = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$2);

	return `<div class="${"background svelte-1e9atp"}" id="${"cfp"}"><div class="${"container svelte-1e9atp"}">${validate_component(Card, "Card").$$render($$result, { center: true }, {}, {
		default: () => `<h3 class="${"svelte-1e9atp"}">Call for initial proposals - Deadline September 18th!</h3>
      <p class="${"svelte-1e9atp"}">If you&#39;re interested in doing a talk, the button below will bring you to the right place! First time doing a
        talk? No Problem! We welcome talks of all levels, from beginner to advanced, long and short. If you have more
        specific questions you can reach us on the <a rel="${"noreferrer"}" target="${"_blank"}" href="${"https://discord.gg/qzfM2JU"}">Svelte discord server
        </a> .
      </p>
      ${validate_component(Button, "Button").$$render(
			$$result,
			{
				href: "https://forms.gle/sGLyg5sLd4kKwRXZ6"
			},
			{},
			{ default: () => `Send proposal` }
		)}`
	})}
    ${validate_component(Card, "Card").$$render($$result, { center: true, darkest: true }, {}, {
		default: () => `<h3 class="${"svelte-1e9atp"}">Looking for sponsors</h3>
      <p class="${"svelte-1e9atp"}">Since last time we&#39;ve decided to try to bring the online experience to another level by improving the quality.
        If you (or your company) are interested in sponsoring the event, reach out to us via email using the link below
        and we can have a chat.
      </p>
      ${validate_component(Button, "Button").$$render(
			$$result,
			{
				href: "mailto:sponsors@sveltesociety.dev",
				black: true
			},
			{},
			{ default: () => `Send email` }
		)}`
	})}</div></div>`;
});

module.exports = CallForPeople;
