'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/Card.svelte generated by Svelte v3.26.0 */

const css = {
	code: ".container.svelte-1nye1v9{padding:35px;background:#1c464d;display:grid;grid-gap:20px;place-items:start}.darkest.svelte-1nye1v9{background:#162b2e}.center.svelte-1nye1v9{margin:0 auto}",
	map: "{\"version\":3,\"file\":\"Card.svelte\",\"sources\":[\"Card.svelte\"],\"sourcesContent\":[\"<script>\\nexport let darkest, center;\\n</script>\\n\\n<style>\\n.container {\\n  padding: 35px;\\n  background: #1c464d;\\n  display: grid;\\n  grid-gap: 20px;\\n  place-items: start;\\n}\\n.darkest {\\n  background: #162b2e;\\n}\\n.center {\\n  margin: 0 auto;\\n}</style>\\n\\n<div class=\\\"container\\\" class:darkest class:center>\\n  <slot />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAKA,UAAU,eAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,UAAU,CAAE,OAAO,CACnB,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CACd,WAAW,CAAE,KAAK,AACpB,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,UAAU,CAAE,OAAO,AACrB,CAAC,AACD,OAAO,eAAC,CAAC,AACP,MAAM,CAAE,CAAC,CAAC,IAAI,AAChB,CAAC\"}"
};

const Card = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { darkest } = $$props, { center } = $$props;
	if ($$props.darkest === void 0 && $$bindings.darkest && darkest !== void 0) $$bindings.darkest(darkest);
	if ($$props.center === void 0 && $$bindings.center && center !== void 0) $$bindings.center(center);
	$$result.css.add(css);

	return `<div class="${[
		"container svelte-1nye1v9",
		(darkest ? "darkest" : "") + " " + (center ? "center" : "")
	].join(" ").trim()}">${slots.default ? slots.default({}) : ``}</div>`;
});

module.exports = Card;
