'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/Sections/FAQ.svelte generated by Svelte v3.26.0 */

const css = {
	code: ".background.svelte-1ntitv7{--small-padding:var(--media-lte-sm) 45px 25px;padding:var(--small-padding, 140px 40px);background:var(--background-dark);display:grid;place-items:center}.container.svelte-1ntitv7{max-width:var(--container-width)}.questions.svelte-1ntitv7{display:grid;grid-gap:40px 50px;--small-grid:var(--media-lte-sm) auto;grid-template-columns:repeat(\n    auto-fit,\n    minmax(var(--small-grid, 350px), 1fr)\n  )}",
	map: "{\"version\":3,\"file\":\"FAQ.svelte\",\"sources\":[\"FAQ.svelte\"],\"sourcesContent\":[\"<style>\\n.background {\\n  --small-padding: var(--media-lte-sm) 45px 25px;\\n  padding: var(--small-padding, 140px 40px);\\n\\n  background: var(--background-dark);\\n  display: grid;\\n  place-items: center;\\n}\\n.container {\\n  max-width: var(--container-width);\\n}\\n.questions {\\n  display: grid;\\n  grid-gap: 40px 50px;\\n\\n  --small-grid: var(--media-lte-sm) auto;\\n  grid-template-columns: repeat(\\n    auto-fit,\\n    minmax(var(--small-grid, 350px), 1fr)\\n  );\\n}</style>\\n\\n<div class=\\\"background\\\" id=\\\"faq\\\">\\n  <div class=\\\"container\\\">\\n    <h2>Frequently Asked Questions</h2>\\n    <div class=\\\"questions\\\">\\n      <slot />\\n    </div>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,WAAW,eAAC,CAAC,AACX,eAAe,CAAE,6BAA6B,CAC9C,OAAO,CAAE,IAAI,eAAe,CAAC,WAAW,CAAC,CAEzC,UAAU,CAAE,IAAI,iBAAiB,CAAC,CAClC,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,AACrB,CAAC,AACD,UAAU,eAAC,CAAC,AACV,SAAS,CAAE,IAAI,iBAAiB,CAAC,AACnC,CAAC,AACD,UAAU,eAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CAAC,IAAI,CAEnB,YAAY,CAAE,wBAAwB,CACtC,qBAAqB,CAAE;IACrB,QAAQ,CAAC;IACT,OAAO,IAAI,YAAY,CAAC,MAAM,CAAC,CAAC,CAAC,GAAG,CAAC;GACtC,AACH,CAAC\"}"
};

const FAQ = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `<div class="${"background svelte-1ntitv7"}" id="${"faq"}"><div class="${"container svelte-1ntitv7"}"><h2>Frequently Asked Questions</h2>
    <div class="${"questions svelte-1ntitv7"}">${slots.default ? slots.default({}) : ``}</div></div></div>`;
});

module.exports = FAQ;
