'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/Sections/Footer.svelte generated by Svelte v3.24.0 */

const css = {
	code: ".container.svelte-1hu0v7a.svelte-1hu0v7a{color:#808080;width:calc(100% - 50px);--small-max-width:var(--media-lte-sm) 300px;max-width:var(--small-max-width, var(--container-width));margin:0 auto;--small-padding:var(--media-lte-sm) 40px 25px 110px 25px;padding:var(--small-padding, 80px 25px 150px 25px);display:grid;grid-gap:30px;--small-grid:var(--media-lte-sm) auto;grid-template-columns:var(--small-grid, auto auto auto);--small-justify:var(--media-lte-sm) center;justify-content:var(--small-justify, space-between);align-items:center;--text-center:var(--media-lte-sm) center;text-align:var(--text-center, initial);line-height:200%}.organised-by.svelte-1hu0v7a.svelte-1hu0v7a{display:grid;place-items:center;grid-gap:10px;grid-template-columns:1fr}.organised-by.svelte-1hu0v7a img.svelte-1hu0v7a{height:60px}.design-by.svelte-1hu0v7a.svelte-1hu0v7a{display:grid;place-items:center;grid-gap:10px;grid-template-columns:1fr}.design-by.svelte-1hu0v7a img.svelte-1hu0v7a{height:30px}",
	map: "{\"version\":3,\"file\":\"Footer.svelte\",\"sources\":[\"Footer.svelte\"],\"sourcesContent\":[\"<style>\\n.container {\\n  color: #808080;\\n  width: calc(100% - 50px);\\n  --small-max-width: var(--media-lte-sm) 300px;\\n  max-width: var(--small-max-width, var(--container-width));\\n  margin: 0 auto;\\n  --small-padding: var(--media-lte-sm) 40px 25px 110px 25px;\\n  padding: var(--small-padding, 80px 25px 150px 25px);\\n\\n  display: grid;\\n  grid-gap: 30px;\\n  --small-grid: var(--media-lte-sm) auto;\\n  grid-template-columns: var(--small-grid, auto auto auto);\\n\\n  --small-justify: var(--media-lte-sm) center;\\n  justify-content: var(--small-justify, space-between);\\n\\n  align-items: center;\\n\\n  --text-center: var(--media-lte-sm) center;\\n  text-align: var(--text-center, initial);\\n\\n  line-height: 200%;\\n}\\n\\n.organised-by {\\n  display: grid;\\n  place-items: center;\\n  grid-gap: 10px;\\n  grid-template-columns: 1fr;\\n}\\n.organised-by img {\\n  height: 60px;\\n}\\n\\n.design-by {\\n  display: grid;\\n  place-items: center;\\n  grid-gap: 10px;\\n  grid-template-columns: 1fr;\\n}\\n\\n.design-by img {\\n  height: 30px;\\n}</style>\\n\\n<div class=\\\"container\\\">\\n  <div class=\\\"info\\\">Svelte Summit is a volunteer effort.</div>\\n  <div class=\\\"organised-by\\\">\\n    <span>Organized by</span><a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https://svelte.school\\\"><img\\n        src=\\\"dist/static/images/svelteschool.svg\\\"\\n        alt=\\\"Svelte School Logo\\\" /></a>\\n  </div>\\n  <div class=\\\"design-by\\\">\\n    <span> Design by </span>\\n    <a\\n      target=\\\"_blank\\\"\\n      rel=\\\"noreferrer\\\"\\n      href=\\\"https://twitter.com/mono_company\\\"><img\\n        src=\\\"dist/static/images/mono.svg\\\"\\n        alt=\\\"mono logo\\\" />\\n    </a>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,UAAU,8BAAC,CAAC,AACV,KAAK,CAAE,OAAO,CACd,KAAK,CAAE,KAAK,IAAI,CAAC,CAAC,CAAC,IAAI,CAAC,CACxB,iBAAiB,CAAE,yBAAyB,CAC5C,SAAS,CAAE,IAAI,iBAAiB,CAAC,uBAAuB,CAAC,CACzD,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,eAAe,CAAE,wCAAwC,CACzD,OAAO,CAAE,IAAI,eAAe,CAAC,qBAAqB,CAAC,CAEnD,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CACd,YAAY,CAAE,wBAAwB,CACtC,qBAAqB,CAAE,IAAI,YAAY,CAAC,eAAe,CAAC,CAExD,eAAe,CAAE,0BAA0B,CAC3C,eAAe,CAAE,IAAI,eAAe,CAAC,cAAc,CAAC,CAEpD,WAAW,CAAE,MAAM,CAEnB,aAAa,CAAE,0BAA0B,CACzC,UAAU,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,CAEvC,WAAW,CAAE,IAAI,AACnB,CAAC,AAED,aAAa,8BAAC,CAAC,AACb,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,CACnB,QAAQ,CAAE,IAAI,CACd,qBAAqB,CAAE,GAAG,AAC5B,CAAC,AACD,4BAAa,CAAC,GAAG,eAAC,CAAC,AACjB,MAAM,CAAE,IAAI,AACd,CAAC,AAED,UAAU,8BAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,CACnB,QAAQ,CAAE,IAAI,CACd,qBAAqB,CAAE,GAAG,AAC5B,CAAC,AAED,yBAAU,CAAC,GAAG,eAAC,CAAC,AACd,MAAM,CAAE,IAAI,AACd,CAAC\"}"
};

const Footer = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css);

	return `<div class="${"container svelte-1hu0v7a"}"><div class="${"info"}">Svelte Summit is a volunteer effort.</div>
  <div class="${"organised-by svelte-1hu0v7a"}"><span>Organized by</span><a target="${"_blank"}" rel="${"noreferrer"}" href="${"https://svelte.school"}"><img src="${"dist/static/images/svelteschool.svg"}" alt="${"Svelte School Logo"}" class="${"svelte-1hu0v7a"}"></a></div>
  <div class="${"design-by svelte-1hu0v7a"}"><span>Design by </span>
    <a target="${"_blank"}" rel="${"noreferrer"}" href="${"https://twitter.com/mono_company"}"><img src="${"dist/static/images/mono.svg"}" alt="${"mono logo"}" class="${"svelte-1hu0v7a"}"></a></div></div>`;
});

module.exports = Footer;
