'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/components/Hero/Background/SVG/BackMountain.svelte generated by Svelte v3.24.0 */

const css = {
	code: "svg.svelte-gm69cn{position:absolute;bottom:0;left:50%;height:25%;--hide-mobile:var(--media-lte-sm) none;display:var(--hide-mobile, initial)}",
	map: "{\"version\":3,\"file\":\"BackMountain.svelte\",\"sources\":[\"BackMountain.svelte\"],\"sourcesContent\":[\"<script>\\nexport let type = \\\"morning\\\";\\nlet color;\\n\\nswitch (type) {\\n  case \\\"morning\\\":\\n    color = \\\"#C4E4E9\\\";\\n    break;\\n  case \\\"evening\\\":\\n    color = \\\"#D5BCBA\\\";\\n    break;\\n  case \\\"night\\\":\\n    color = \\\"#12262A\\\";\\n    break;\\n\\n  default:\\n    break;\\n}\\n</script>\\n\\n<style>\\nsvg {\\n  position: absolute;\\n  bottom: 0;\\n  left: 50%;\\n\\n  height: 25%;\\n\\n  --hide-mobile: var(--media-lte-sm) none;\\n  display: var(--hide-mobile, initial);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 1412 289\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    d=\\\"M132.873 91.4783C132.873 91.4783 55.3632 236.986 0 289H1411.5L1110\\n    124.5L834.5 76.5L641.5 0L412.782 45.7301C349.277 64.468 132.873 91.4783\\n    132.873 91.4783Z\\\"\\n    fill={color} />\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAqBA,GAAG,cAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,CAAC,CACT,IAAI,CAAE,GAAG,CAET,MAAM,CAAE,GAAG,CAEX,aAAa,CAAE,wBAAwB,CACvC,OAAO,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,AACtC,CAAC\"}"
};

const BackMountain = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type = "morning" } = $$props;
	let color;

	switch (type) {
		case "morning":
			color = "#C4E4E9";
			break;
		case "evening":
			color = "#D5BCBA";
			break;
		case "night":
			color = "#12262A";
			break;
	}

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css);
	return `<svg viewBox="${"0 0 1412 289"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-gm69cn"}"><path d="${"M132.873 91.4783C132.873 91.4783 55.3632 236.986 0 289H1411.5L1110\n    124.5L834.5 76.5L641.5 0L412.782 45.7301C349.277 64.468 132.873 91.4783\n    132.873 91.4783Z"}"${add_attribute("fill", color, 0)}></path></svg>`;
});

/* src/components/Hero/Background/SVG/FrontMountain.svelte generated by Svelte v3.24.0 */

const css$1 = {
	code: "svg.svelte-1n305uu{position:absolute;bottom:0;left:0%;height:45%;--hide-mobile:var(--media-lte-sm) none;display:var(--hide-mobile, initial)}",
	map: "{\"version\":3,\"file\":\"FrontMountain.svelte\",\"sources\":[\"FrontMountain.svelte\"],\"sourcesContent\":[\"<script>\\nexport let type = \\\"morning\\\";\\nlet color;\\n\\nswitch (type) {\\n  case \\\"morning\\\":\\n    color = \\\"#D5E2E4\\\";\\n    break;\\n  case \\\"evening\\\":\\n    color = \\\"#F5E6D4\\\";\\n    break;\\n  case \\\"night\\\":\\n    color = \\\"#D5E2E4\\\";\\n    break;\\n\\n  default:\\n    break;\\n}\\n</script>\\n\\n<style>\\nsvg {\\n  position: absolute;\\n  bottom: 0;\\n  left: 0%;\\n\\n  height: 45%;\\n\\n  --hide-mobile: var(--media-lte-sm) none;\\n  display: var(--hide-mobile, initial);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 910 535\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    d=\\\"M96.5 210.5C96.5 210.5 40.2079 449.549 0 535H910L724.63 410.804L581.832\\n    318.452L404.444 0L299.786 135.342C253.665 166.126 96.5 210.5 96.5 210.5Z\\\"\\n    fill={color} />\\n  <path\\n    opacity=\\\"0.1\\\"\\n    d=\\\"M408.49 230.931L479 137L431.302 230.931L278.357 345.101L255.027\\n    534H170L242.065 345.101L408.49 230.931Z\\\"\\n    fill=\\\"black\\\" />\\n  <path\\n    d=\\\"M509.5 418L576 312L530 418L576 496L615 535H576L530 496L509.5 418Z\\\"\\n    fill=\\\"#C0CBCD\\\" />\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAqBA,GAAG,eAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,CAAC,CACT,IAAI,CAAE,EAAE,CAER,MAAM,CAAE,GAAG,CAEX,aAAa,CAAE,wBAAwB,CACvC,OAAO,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,AACtC,CAAC\"}"
};

const FrontMountain = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type = "morning" } = $$props;
	let color;

	switch (type) {
		case "morning":
			color = "#D5E2E4";
			break;
		case "evening":
			color = "#F5E6D4";
			break;
		case "night":
			color = "#D5E2E4";
			break;
	}

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css$1);
	return `<svg viewBox="${"0 0 910 535"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-1n305uu"}"><path d="${"M96.5 210.5C96.5 210.5 40.2079 449.549 0 535H910L724.63 410.804L581.832\n    318.452L404.444 0L299.786 135.342C253.665 166.126 96.5 210.5 96.5 210.5Z"}"${add_attribute("fill", color, 0)}></path><path opacity="${"0.1"}" d="${"M408.49 230.931L479 137L431.302 230.931L278.357 345.101L255.027\n    534H170L242.065 345.101L408.49 230.931Z"}" fill="${"black"}"></path><path d="${"M509.5 418L576 312L530 418L576 496L615 535H576L530 496L509.5 418Z"}" fill="${"#C0CBCD"}"></path></svg>`;
});

/* src/components/Hero/Background/SVG/MidMountain.svelte generated by Svelte v3.24.0 */

const css$2 = {
	code: "svg.svelte-1n9lvnt{position:absolute;bottom:0;--center-mobile:var(--media-lte-sm) 50%;left:var(--center-mobile, 20%);right:var(--center-mobile, initial);--translate-mobile:var(--media-lte-sm) -50%;transform:translateX(var(--translate-mobile, initial));--height:var(--media-lte-sm) 80%;height:var(--height, 60%)}",
	map: "{\"version\":3,\"file\":\"MidMountain.svelte\",\"sources\":[\"MidMountain.svelte\"],\"sourcesContent\":[\"<script>\\nexport let type = \\\"morning\\\";\\nlet color;\\n\\nswitch (type) {\\n  case \\\"morning\\\":\\n    color = \\\"#B9D7DB\\\";\\n    break;\\n  case \\\"evening\\\":\\n    color = \\\"#F2DBBF\\\";\\n    break;\\n  case \\\"night\\\":\\n    color = \\\"#F2F5F5\\\";\\n    break;\\n\\n  default:\\n    break;\\n}\\n</script>\\n\\n<style>\\nsvg {\\n  position: absolute;\\n  bottom: 0;\\n  --center-mobile: var(--media-lte-sm) 50%;\\n  left: var(--center-mobile, 20%);\\n  right: var(--center-mobile, initial);\\n  --translate-mobile: var(--media-lte-sm) -50%;\\n  transform: translateX(var(--translate-mobile, initial));\\n\\n  --height: var(--media-lte-sm) 80%;\\n  height: var(--height, 60%);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 1253 646\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    d=\\\"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\\n    490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873 240.924\\n    132.873 240.924Z\\\"\\n    fill={color} />\\n  <mask\\n    id=\\\"mask0\\\"\\n    mask-type=\\\"alpha\\\"\\n    maskUnits=\\\"userSpaceOnUse\\\"\\n    x=\\\"0\\\"\\n    y=\\\"0\\\"\\n    width=\\\"1253\\\"\\n    height=\\\"646\\\">\\n    <path\\n      d=\\\"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\\n      490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873\\n      240.924 132.873 240.924Z\\\"\\n      fill=\\\"#B9D7DB\\\" />\\n  </mask>\\n  <g mask=\\\"url(#mask0)\\\">\\n    <path\\n      opacity=\\\"0.1\\\"\\n      d=\\\"M751.669 245.016L711.809 157L733.011 254.713L739.372 313.639L742.753\\n      521L875.809 649H929.809L778.809 521L760.998 294.94L751.669 245.016Z\\\"\\n      fill=\\\"black\\\" />\\n    <path\\n      opacity=\\\"0.05\\\"\\n      d=\\\"M345.918 617.142L289.207 660.194L357.029 635.279L395.231 612.383L509.48\\n      613.488L669.807 414L499.932 590.006L380.419 598.519L345.918 617.142Z\\\"\\n      fill=\\\"black\\\" />\\n    <path\\n      d=\\\"M413 41.5222L522.5 94.8728H584.5H630L716.5 77.3062L785 -17.684L611.5\\n      -140L502 -100.963L413 41.5222Z\\\"\\n      fill=\\\"white\\\" />\\n  </g>\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAqBA,GAAG,eAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,CAAC,CACT,eAAe,CAAE,uBAAuB,CACxC,IAAI,CAAE,IAAI,eAAe,CAAC,IAAI,CAAC,CAC/B,KAAK,CAAE,IAAI,eAAe,CAAC,QAAQ,CAAC,CACpC,kBAAkB,CAAE,wBAAwB,CAC5C,SAAS,CAAE,WAAW,IAAI,kBAAkB,CAAC,QAAQ,CAAC,CAAC,CAEvD,QAAQ,CAAE,uBAAuB,CACjC,MAAM,CAAE,IAAI,QAAQ,CAAC,IAAI,CAAC,AAC5B,CAAC\"}"
};

const MidMountain = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type = "morning" } = $$props;
	let color;

	switch (type) {
		case "morning":
			color = "#B9D7DB";
			break;
		case "evening":
			color = "#F2DBBF";
			break;
		case "night":
			color = "#F2F5F5";
			break;
	}

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css$2);
	return `<svg viewBox="${"0 0 1253 646"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-1n9lvnt"}"><path d="${"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\n    490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873 240.924\n    132.873 240.924Z"}"${add_attribute("fill", color, 0)}></path><mask id="${"mask0"}" mask-type="${"alpha"}" maskUnits="${"userSpaceOnUse"}" x="${"0"}" y="${"0"}" width="${"1253"}" height="${"646"}"><path d="${"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\n      490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873\n      240.924 132.873 240.924Z"}" fill="${"#B9D7DB"}"></path></mask><g mask="${"url(#mask0)"}"><path opacity="${"0.1"}" d="${"M751.669 245.016L711.809 157L733.011 254.713L739.372 313.639L742.753\n      521L875.809 649H929.809L778.809 521L760.998 294.94L751.669 245.016Z"}" fill="${"black"}"></path><path opacity="${"0.05"}" d="${"M345.918 617.142L289.207 660.194L357.029 635.279L395.231 612.383L509.48\n      613.488L669.807 414L499.932 590.006L380.419 598.519L345.918 617.142Z"}" fill="${"black"}"></path><path d="${"M413 41.5222L522.5 94.8728H584.5H630L716.5 77.3062L785 -17.684L611.5\n      -140L502 -100.963L413 41.5222Z"}" fill="${"white"}"></path></g></svg>`;
});

/* src/components/Hero/Background/SVG/Bears.svelte generated by Svelte v3.24.0 */

const css$3 = {
	code: ".bears-normal.svelte-1764xpx{width:92px;height:44px;position:absolute;bottom:-11px;left:15%;transform:scale(1.1)}",
	map: "{\"version\":3,\"file\":\"Bears.svelte\",\"sources\":[\"Bears.svelte\"],\"sourcesContent\":[\"<style>\\n.bears-normal {\\n  width: 92px;\\n  height: 44px;\\n  position: absolute;\\n  bottom: -11px;\\n  left: 15%;\\n  transform: scale(1.1);\\n}</style>\\n\\n<svg width=\\\"92\\\" height=\\\"22\\\" class=\\\"bears-normal\\\" viewBox=\\\"0 0 92 22\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n<path d=\\\"M59.1117 0L78.676 2.11327L87.9314 7.4133L88.4841 8.46383L91.4499 9.98178C91.4499 9.98178 91.0099 13.1654 86.9906 12.1148L80.4391 9.95742L74.5988 13.8933L72.1674 21.8028H69.0142L69.0127 13.8859H58.005L55.6268 21.8028H52.4736V10.0689L59.1117 0Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M80.0586 11.2015L76.4883 16.3597L78.466 21.8027H81.6618L80.0586 11.2015Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M61.2466 18.7285L64.4774 14.493L65.6391 21.8026H62.4311L61.2466 18.7285Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M4.76821 6.31155L18.8214 7.82954L25.4696 11.6366L25.8666 12.3912L27.9971 13.4816C27.9971 13.4816 27.681 15.7684 24.7939 15.0138L20.0879 13.4641L15.8927 16.2912L14.1462 21.9727H11.8813L11.8802 16.2859H3.9732L2.26492 21.9727H0V13.5441L4.76821 6.31155Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M19.8146 14.3582L17.25 18.0633L18.6706 21.9732H20.9662L19.8146 14.3582Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M6.30127 19.7641L8.62199 16.7216L9.45645 21.9722H7.15213L6.30127 19.7641Z\\\" fill=\\\"#7B5855\\\"/>\\n</svg>\\n\\n\"],\"names\":[],\"mappings\":\"AACA,aAAa,eAAC,CAAC,AACb,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,IAAI,CACZ,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,KAAK,CACb,IAAI,CAAE,GAAG,CACT,SAAS,CAAE,MAAM,GAAG,CAAC,AACvB,CAAC\"}"
};

const Bears = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$3);
	return `<svg width="${"92"}" height="${"22"}" class="${"bears-normal svelte-1764xpx"}" viewBox="${"0 0 92 22"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}"><path d="${"M59.1117 0L78.676 2.11327L87.9314 7.4133L88.4841 8.46383L91.4499 9.98178C91.4499 9.98178 91.0099 13.1654 86.9906 12.1148L80.4391 9.95742L74.5988 13.8933L72.1674 21.8028H69.0142L69.0127 13.8859H58.005L55.6268 21.8028H52.4736V10.0689L59.1117 0Z"}" fill="${"#7B5855"}"></path><path d="${"M80.0586 11.2015L76.4883 16.3597L78.466 21.8027H81.6618L80.0586 11.2015Z"}" fill="${"#7B5855"}"></path><path d="${"M61.2466 18.7285L64.4774 14.493L65.6391 21.8026H62.4311L61.2466 18.7285Z"}" fill="${"#7B5855"}"></path><path d="${"M4.76821 6.31155L18.8214 7.82954L25.4696 11.6366L25.8666 12.3912L27.9971 13.4816C27.9971 13.4816 27.681 15.7684 24.7939 15.0138L20.0879 13.4641L15.8927 16.2912L14.1462 21.9727H11.8813L11.8802 16.2859H3.9732L2.26492 21.9727H0V13.5441L4.76821 6.31155Z"}" fill="${"#7B5855"}"></path><path d="${"M19.8146 14.3582L17.25 18.0633L18.6706 21.9732H20.9662L19.8146 14.3582Z"}" fill="${"#7B5855"}"></path><path d="${"M6.30127 19.7641L8.62199 16.7216L9.45645 21.9722H7.15213L6.30127 19.7641Z"}" fill="${"#7B5855"}"></path></svg>`;
});

/* src/components/Hero/Background/SVG/Reflection.svelte generated by Svelte v3.24.0 */

const css$4 = {
	code: "svg.svelte-icy12y{position:absolute;bottom:-20%;left:20%;height:25%;--hide-mobile:var(--media-lte-sm) none;display:var(--hide-mobile, initial)}",
	map: "{\"version\":3,\"file\":\"Reflection.svelte\",\"sources\":[\"Reflection.svelte\"],\"sourcesContent\":[\"<style>\\nsvg {\\n  position: absolute;\\n  bottom: -20%;\\n  left: 20%;\\n\\n  height: 25%;\\n\\n  --hide-mobile: var(--media-lte-sm) none;\\n  display: var(--hide-mobile, initial);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 1412 178\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    opacity=\\\"0.1\\\"\\n    d=\\\"M1279.08 120.98C1355.41 88.45 1356.62 31.8581 1412\\n    0.00012207L-0.000106509 -1.37066e-06C-0.000106509 -1.37066e-06 174.204\\n    74.9833 301.607 100.755C405.341 121.738 472.521 111.018 577.204\\n    130.154C654.919 144.361 689.633 171.697 770.273 177.01C860.87 182.979\\n    935.545 160.477 999.072 149.001C1062.6 137.524 1188.14 159.738 1279.08\\n    120.98Z\\\"\\n    fill=\\\"#C1DADF\\\" />\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AACA,GAAG,cAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,IAAI,CACZ,IAAI,CAAE,GAAG,CAET,MAAM,CAAE,GAAG,CAEX,aAAa,CAAE,wBAAwB,CACvC,OAAO,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,AACtC,CAAC\"}"
};

const Reflection = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$4);
	return `<svg viewBox="${"0 0 1412 178"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-icy12y"}"><path opacity="${"0.1"}" d="${"M1279.08 120.98C1355.41 88.45 1356.62 31.8581 1412\n    0.00012207L-0.000106509 -1.37066e-06C-0.000106509 -1.37066e-06 174.204\n    74.9833 301.607 100.755C405.341 121.738 472.521 111.018 577.204\n    130.154C654.919 144.361 689.633 171.697 770.273 177.01C860.87 182.979\n    935.545 160.477 999.072 149.001C1062.6 137.524 1188.14 159.738 1279.08\n    120.98Z"}" fill="${"#C1DADF"}"></path></svg>`;
});

/* src/components/Hero/Background/SVG/MorningSun.svelte generated by Svelte v3.24.0 */

const css$5 = {
	code: "img.svelte-76ztoc{position:absolute;--moon-display:var(--media-lte-sm) none;display:var(--moon-display, initial);top:55%;right:5%;height:275px}",
	map: "{\"version\":3,\"file\":\"MorningSun.svelte\",\"sources\":[\"MorningSun.svelte\"],\"sourcesContent\":[\"<style>\\nimg {\\n  position: absolute;\\n  --moon-display: var(--media-lte-sm) none;\\n  display: var(--moon-display, initial);\\n  top: 55%;\\n  right: 5%;\\n  height: 275px;\\n}</style>\\n\\n<img src=\\\"/dist/static/images/morning-sun.svg\\\" alt=\\\"A moon\\\" />\\n\"],\"names\":[],\"mappings\":\"AACA,GAAG,cAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,cAAc,CAAE,wBAAwB,CACxC,OAAO,CAAE,IAAI,cAAc,CAAC,QAAQ,CAAC,CACrC,GAAG,CAAE,GAAG,CACR,KAAK,CAAE,EAAE,CACT,MAAM,CAAE,KAAK,AACf,CAAC\"}"
};

const MorningSun = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$5);
	return `<img src="${"/dist/static/images/morning-sun.svg"}" alt="${"A moon"}" class="${"svelte-76ztoc"}">`;
});

/* src/components/Hero/Background/Background.svelte generated by Svelte v3.24.0 */

const css$6 = {
	code: ".container.svelte-spzizf{overflow:hidden;position:absolute;top:0;bottom:0;left:0;right:0;z-index:-1;background:#d6f1f5}",
	map: "{\"version\":3,\"file\":\"Background.svelte\",\"sources\":[\"Background.svelte\"],\"sourcesContent\":[\"<script>\\nimport { BackMountain, MidMountain, FrontMountain, Reflection, Bears, MorningSun } from './SVG/';\\n</script>\\n\\n<style>\\n.container {\\n  overflow: hidden;\\n  position: absolute;\\n  top: 0;\\n  bottom: 0;\\n  left: 0;\\n  right: 0;\\n  z-index: -1;\\n\\n  background: #d6f1f5;\\n}</style>\\n\\n<div class=\\\"container\\\">\\n  <MorningSun />\\n  <BackMountain type=\\\"morning\\\" />\\n  <MidMountain type=\\\"morning\\\" />\\n  <FrontMountain type=\\\"morning\\\" />\\n  <Bears />\\n  <Reflection />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAKA,UAAU,cAAC,CAAC,AACV,QAAQ,CAAE,MAAM,CAChB,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,CAAC,CACN,MAAM,CAAE,CAAC,CACT,IAAI,CAAE,CAAC,CACP,KAAK,CAAE,CAAC,CACR,OAAO,CAAE,EAAE,CAEX,UAAU,CAAE,OAAO,AACrB,CAAC\"}"
};

const Background = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$6);

	return `<div class="${"container svelte-spzizf"}">${validate_component(MorningSun, "MorningSun").$$render($$result, {}, {}, {})}
  ${validate_component(BackMountain, "BackMountain").$$render($$result, { type: "morning" }, {}, {})}
  ${validate_component(MidMountain, "MidMountain").$$render($$result, { type: "morning" }, {}, {})}
  ${validate_component(FrontMountain, "FrontMountain").$$render($$result, { type: "morning" }, {}, {})}
  ${validate_component(Bears, "Bears").$$render($$result, {}, {}, {})}
  ${validate_component(Reflection, "Reflection").$$render($$result, {}, {}, {})}</div>`;
});

/* src/components/Hero/Info.svelte generated by Svelte v3.24.0 */

const css$7 = {
	code: ".info.svelte-1gnpq5v{display:grid;grid-gap:12px;--columns-small:var(--media-lte-sm) 2fr 3fr;grid-template-columns:var(--columns-small, 1fr);--small-placement:var(--media-lte-sm) start end;place-items:var(--small-placement, start)}time.svelte-1gnpq5v{line-height:105%;--small:var(--media-lte-sm) 40px;display:grid;--small-placement:var(--media-lte-sm) end;place-items:var(--small-placement, center start);--small:var(--media-lte-sm) 50px;font-size:var(--small, 73px)}span.svelte-1gnpq5v{--align-text-mobile:var(--media-lte-sm) right;text-align:var(--align-text-mobile, initial)}.sub.svelte-1gnpq5v{--small:var(--media-lte-sm) 33px;font-size:var(--small, 40px);--small-line:var(--media-lte-sm) 100%;line-height:var(--small-line, 105%);display:grid;--small-placement:var(--media-lte-sm) left;text-align:var(--small-placement, left);--small-width:var(--media-lte-sm) 250px;max-width:var(--small-width, 300px)}",
	map: "{\"version\":3,\"file\":\"Info.svelte\",\"sources\":[\"Info.svelte\"],\"sourcesContent\":[\"<style>\\n.info {\\n  display: grid;\\n  grid-gap: 12px;\\n\\n  --columns-small: var(--media-lte-sm) 2fr 3fr;\\n  grid-template-columns: var(--columns-small, 1fr);\\n\\n  --small-placement: var(--media-lte-sm) start end;\\n  place-items: var(--small-placement, start);\\n}\\ntime {\\n  line-height: 105%;\\n  --small: var(--media-lte-sm) 40px;\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) end;\\n  place-items: var(--small-placement, center start);\\n  --small: var(--media-lte-sm) 50px;\\n  font-size: var(--small, 73px);\\n}\\nspan {\\n  --align-text-mobile: var(--media-lte-sm) right;\\n  text-align: var(--align-text-mobile, initial);\\n}\\n.sub {\\n  --small: var(--media-lte-sm) 33px;\\n  font-size: var(--small, 40px);\\n\\n  --small-line: var(--media-lte-sm) 100%;\\n  line-height: var(--small-line, 105%);\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) left;\\n  text-align: var(--small-placement, left);\\n\\n  --small-width: var(--media-lte-sm) 250px;\\n  max-width: var(--small-width, 300px);\\n}</style>\\n\\n<div class=\\\"info\\\">\\n  <time class=\\\"display\\\" datetime=\\\"2020-10-18\\\">\\n    <span>OCT 18</span>\\n    <span>2020</span>\\n  </time>\\n  <div class=\\\"sub display\\\">THE 2ND VIRTUAL CONFERENCE ABOUT SVELTE</div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,KAAK,eAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CAEd,eAAe,CAAE,2BAA2B,CAC5C,qBAAqB,CAAE,IAAI,eAAe,CAAC,IAAI,CAAC,CAEhD,iBAAiB,CAAE,6BAA6B,CAChD,WAAW,CAAE,IAAI,iBAAiB,CAAC,MAAM,CAAC,AAC5C,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,WAAW,CAAE,IAAI,CACjB,OAAO,CAAE,wBAAwB,CAEjC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,uBAAuB,CAC1C,WAAW,CAAE,IAAI,iBAAiB,CAAC,aAAa,CAAC,CACjD,OAAO,CAAE,wBAAwB,CACjC,SAAS,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC/B,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,mBAAmB,CAAE,yBAAyB,CAC9C,UAAU,CAAE,IAAI,mBAAmB,CAAC,QAAQ,CAAC,AAC/C,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,OAAO,CAAE,wBAAwB,CACjC,SAAS,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,CAE7B,YAAY,CAAE,wBAAwB,CACtC,WAAW,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CAEpC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,wBAAwB,CAC3C,UAAU,CAAE,IAAI,iBAAiB,CAAC,KAAK,CAAC,CAExC,aAAa,CAAE,yBAAyB,CACxC,SAAS,CAAE,IAAI,aAAa,CAAC,MAAM,CAAC,AACtC,CAAC\"}"
};

const Info = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$7);

	return `<div class="${"info svelte-1gnpq5v"}"><time class="${"display svelte-1gnpq5v"}" datetime="${"2020-10-18"}"><span class="${"svelte-1gnpq5v"}">OCT 18</span>
    <span class="${"svelte-1gnpq5v"}">2020</span></time>
  <div class="${"sub display svelte-1gnpq5v"}">THE 2ND VIRTUAL CONFERENCE ABOUT SVELTE</div></div>`;
});

/* src/components/Hero/Title.svelte generated by Svelte v3.24.0 */

const css$8 = {
	code: "h1.svelte-16fjkkh{-webkit-margin-before:0;margin-block-start:0;-webkit-margin-after:0;margin-block-end:0;--small-margin:var(--media-lte-sm) 0px;margin-top:var(--small-margin, 155px);display:grid;--small-placement:var(--media-lte-sm) center;place-items:var(--small-placement, center end)}.leading.svelte-16fjkkh{color:var(--background-darkest)}.lagging.svelte-16fjkkh{color:var(--background)}",
	map: "{\"version\":3,\"file\":\"Title.svelte\",\"sources\":[\"Title.svelte\"],\"sourcesContent\":[\"<style>\\nh1 {\\n  -webkit-margin-before: 0;\\n          margin-block-start: 0;\\n  -webkit-margin-after: 0;\\n          margin-block-end: 0;\\n  --small-margin: var(--media-lte-sm) 0px;\\n  margin-top: var(--small-margin, 155px);\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) center;\\n  place-items: var(--small-placement, center end);\\n}\\n.leading {\\n  color: var(--background-darkest);\\n}\\n.lagging {\\n  color: var(--background);\\n}</style>\\n\\n<h1 class=\\\"display\\\">\\n  <span class=\\\"leading\\\">SVELTE</span>\\n  <span class=\\\"lagging\\\">SUMMIT</span>\\n</h1>\\n\"],\"names\":[],\"mappings\":\"AACA,EAAE,eAAC,CAAC,AACF,qBAAqB,CAAE,CAAC,CAChB,kBAAkB,CAAE,CAAC,CAC7B,oBAAoB,CAAE,CAAC,CACf,gBAAgB,CAAE,CAAC,CAC3B,cAAc,CAAE,uBAAuB,CACvC,UAAU,CAAE,IAAI,cAAc,CAAC,MAAM,CAAC,CAEtC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,0BAA0B,CAC7C,WAAW,CAAE,IAAI,iBAAiB,CAAC,WAAW,CAAC,AACjD,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,KAAK,CAAE,IAAI,oBAAoB,CAAC,AAClC,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,KAAK,CAAE,IAAI,YAAY,CAAC,AAC1B,CAAC\"}"
};

const Title = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$8);

	return `<h1 class="${"display svelte-16fjkkh"}"><span class="${"leading svelte-16fjkkh"}">SVELTE</span>
  <span class="${"lagging svelte-16fjkkh"}">SUMMIT</span></h1>`;
});

/* src/components/Hero/Hero.svelte generated by Svelte v3.24.0 */

const css$9 = {
	code: ".container.svelte-1a5c3ok{position:relative;z-index:1001;--small-padding:var(--media-lte-sm) 43px;padding-bottom:var(--small-padding, 125px);display:grid;--small-gap:var(--media-lte-sm) 42px;--medium-gap:var(--media-md) 42px;grid-gap:var(--small-gap, var(--medium-gap, 82px));place-items:start center}.logo.svelte-1a5c3ok{display:grid;place-items:center;--small-padding:var(--media-lte-sm) 43px;padding-top:var(--small-padding, 125px);--small:var(--media-lte-sm) 21px;grid-gap:var(--small, 34px)}img.svelte-1a5c3ok{--small:var(--media-lte-sm) 65px;height:var(--small, 85px);width:var(--small, 85px)}.present.svelte-1a5c3ok{font-size:14px;line-height:150%;letter-spacing:0.5em;text-transform:uppercase;color:#38332d}.text.svelte-1a5c3ok{display:grid;--columns-small:var(--media-lte-sm) 1fr;grid-template-columns:var(--columns-small, auto auto);--small-gap:var(--media-lte-sm) 30px;grid-gap:var(--small-gap, 40px);--mobile-justify:var(--media-lte-sm);justify-self:var(--small-gap, end);--mobile-margin-offset:var(--media-lte-sm) 0;margin-right:var(--mobile-margin-offset, 15vw);padding:0 20px;place-items:start center;color:var(--background);line-height:125%}",
	map: "{\"version\":3,\"file\":\"Hero.svelte\",\"sources\":[\"Hero.svelte\"],\"sourcesContent\":[\"<script>\\nimport { Background } from \\\"./Background/\\\";\\nimport Navigation from \\\"./Navigation.svelte\\\";\\nimport Info from \\\"./Info.svelte\\\";\\nimport Title from \\\"./Title.svelte\\\";\\n\\nconst menu = [\\n  {\\n    name: \\\"Intro\\\",\\n    url: \\\"#intro\\\",\\n  },\\n  {\\n    name: \\\"Sponsors\\\",\\n    url: \\\"#sponsors\\\",\\n  },\\n  {\\n    name: \\\"Speakers\\\",\\n    url: \\\"#speakers\\\",\\n  },\\n  {\\n    name: \\\"FAQ\\\",\\n    url: \\\"#faq\\\",\\n  },\\n];\\n</script>\\n\\n<style>\\n.container {\\n  position: relative;\\n  z-index: 1001;\\n\\n  --small-padding: var(--media-lte-sm) 43px;\\n  padding-bottom: var(--small-padding, 125px);\\n\\n  display: grid;\\n  --small-gap: var(--media-lte-sm) 42px;\\n  --medium-gap: var(--media-md) 42px;\\n  grid-gap: var(--small-gap, var(--medium-gap, 82px));\\n  place-items: start center;\\n}\\n\\n.logo {\\n  display: grid;\\n  place-items: center;\\n  --small-padding: var(--media-lte-sm) 43px;\\n  padding-top: var(--small-padding, 125px);\\n\\n  --small: var(--media-lte-sm) 21px;\\n  grid-gap: var(--small, 34px);\\n}\\n\\nimg {\\n  --small: var(--media-lte-sm) 65px;\\n  height: var(--small, 85px);\\n  width: var(--small, 85px);\\n}\\n\\n.present {\\n  font-size: 14px;\\n  line-height: 150%;\\n  letter-spacing: 0.5em;\\n  text-transform: uppercase;\\n\\n  color: #38332d;\\n}\\n.text {\\n  display: grid;\\n  --columns-small: var(--media-lte-sm) 1fr;\\n  grid-template-columns: var(--columns-small, auto auto);\\n\\n  --small-gap: var(--media-lte-sm) 30px;\\n  grid-gap: var(--small-gap, 40px);\\n\\n  --mobile-justify: var(--media-lte-sm);\\n  justify-self: var(--small-gap, end);\\n\\n  --mobile-margin-offset: var(--media-lte-sm) 0;\\n  margin-right: var(--mobile-margin-offset, 15vw);\\n\\n  padding: 0 20px;\\n\\n  place-items: start center;\\n  color: var(--background);\\n  line-height: 125%;\\n}</style>\\n\\n<div class=\\\"container\\\" id=\\\"intro\\\">\\n  <div class=\\\"ejs-component\\\" data-ejs-component=\\\"Navigation\\\" data-ejs-props={JSON.stringify({ menu })} data-ejs-options={JSON.stringify({\\\"loading\\\":\\\"lazy\\\"})} />\\n  <div class=\\\"logo\\\">\\n    <a href=\\\"https://sveltesociety.dev/\\\"><img\\n        src=\\\"/dist/static/images/svelte-society-logo.svg\\\"\\n        alt=\\\"Svelte Society\\\" /></a>\\n    <span class=\\\"present\\\">presents</span>\\n  </div>\\n  <div class=\\\"text\\\">\\n    <Title />\\n    <Info />\\n  </div>\\n  <Background />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AA2BA,UAAU,eAAC,CAAC,AACV,QAAQ,CAAE,QAAQ,CAClB,OAAO,CAAE,IAAI,CAEb,eAAe,CAAE,wBAAwB,CACzC,cAAc,CAAE,IAAI,eAAe,CAAC,MAAM,CAAC,CAE3C,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,wBAAwB,CACrC,YAAY,CAAE,oBAAoB,CAClC,QAAQ,CAAE,IAAI,WAAW,CAAC,wBAAwB,CAAC,CACnD,WAAW,CAAE,KAAK,CAAC,MAAM,AAC3B,CAAC,AAED,KAAK,eAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,CACnB,eAAe,CAAE,wBAAwB,CACzC,WAAW,CAAE,IAAI,eAAe,CAAC,MAAM,CAAC,CAExC,OAAO,CAAE,wBAAwB,CACjC,QAAQ,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC9B,CAAC,AAED,GAAG,eAAC,CAAC,AACH,OAAO,CAAE,wBAAwB,CACjC,MAAM,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,CAC1B,KAAK,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC3B,CAAC,AAED,QAAQ,eAAC,CAAC,AACR,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,IAAI,CACjB,cAAc,CAAE,KAAK,CACrB,cAAc,CAAE,SAAS,CAEzB,KAAK,CAAE,OAAO,AAChB,CAAC,AACD,KAAK,eAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,uBAAuB,CACxC,qBAAqB,CAAE,IAAI,eAAe,CAAC,UAAU,CAAC,CAEtD,WAAW,CAAE,wBAAwB,CACrC,QAAQ,CAAE,IAAI,WAAW,CAAC,KAAK,CAAC,CAEhC,gBAAgB,CAAE,mBAAmB,CACrC,YAAY,CAAE,IAAI,WAAW,CAAC,IAAI,CAAC,CAEnC,sBAAsB,CAAE,qBAAqB,CAC7C,YAAY,CAAE,IAAI,sBAAsB,CAAC,KAAK,CAAC,CAE/C,OAAO,CAAE,CAAC,CAAC,IAAI,CAEf,WAAW,CAAE,KAAK,CAAC,MAAM,CACzB,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,WAAW,CAAE,IAAI,AACnB,CAAC\"}"
};

const Hero = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	const menu = [
		{ name: "Intro", url: "#intro" },
		{ name: "Sponsors", url: "#sponsors" },
		{ name: "Speakers", url: "#speakers" },
		{ name: "FAQ", url: "#faq" }
	];

	$$result.css.add(css$9);

	return `<div class="${"container svelte-1a5c3ok"}" id="${"intro"}"><div class="${"ejs-component"}" data-ejs-component="${"Navigation"}"${add_attribute("data-ejs-props", JSON.stringify({ menu }), 0)}${add_attribute("data-ejs-options", JSON.stringify({ "loading": "lazy" }), 0)}></div>
  <div class="${"logo svelte-1a5c3ok"}"><a href="${"https://sveltesociety.dev/"}"><img src="${"/dist/static/images/svelte-society-logo.svg"}" alt="${"Svelte Society"}" class="${"svelte-1a5c3ok"}"></a>
    <span class="${"present svelte-1a5c3ok"}">presents</span></div>
  <div class="${"text svelte-1a5c3ok"}">${validate_component(Title, "Title").$$render($$result, {}, {}, {})}
    ${validate_component(Info, "Info").$$render($$result, {}, {}, {})}</div>
  ${validate_component(Background, "Background").$$render($$result, {}, {}, {})}</div>`;
});

module.exports = Hero;
