'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/components/Hero/Background/SVG/BackMountain.svelte generated by Svelte v3.24.0 */

const css = {
	code: "svg.svelte-gm69cn{position:absolute;bottom:0;left:50%;height:25%;--hide-mobile:var(--media-lte-sm) none;display:var(--hide-mobile, initial)}",
	map: "{\"version\":3,\"file\":\"BackMountain.svelte\",\"sources\":[\"BackMountain.svelte\"],\"sourcesContent\":[\"<script>\\nexport let type = \\\"morning\\\";\\nlet color;\\n\\nswitch (type) {\\n  case \\\"morning\\\":\\n    color = \\\"#C4E4E9\\\";\\n    break;\\n  case \\\"evening\\\":\\n    color = \\\"#D5BCBA\\\";\\n    break;\\n  case \\\"night\\\":\\n    color = \\\"#12262A\\\";\\n    break;\\n\\n  default:\\n    break;\\n}\\n</script>\\n\\n<style>\\nsvg {\\n  position: absolute;\\n  bottom: 0;\\n  left: 50%;\\n\\n  height: 25%;\\n\\n  --hide-mobile: var(--media-lte-sm) none;\\n  display: var(--hide-mobile, initial);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 1412 289\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    d=\\\"M132.873 91.4783C132.873 91.4783 55.3632 236.986 0 289H1411.5L1110\\n    124.5L834.5 76.5L641.5 0L412.782 45.7301C349.277 64.468 132.873 91.4783\\n    132.873 91.4783Z\\\"\\n    fill={color} />\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAqBA,GAAG,cAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,CAAC,CACT,IAAI,CAAE,GAAG,CAET,MAAM,CAAE,GAAG,CAEX,aAAa,CAAE,wBAAwB,CACvC,OAAO,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,AACtC,CAAC\"}"
};

const BackMountain = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type = "morning" } = $$props;
	let color;

	switch (type) {
		case "morning":
			color = "#C4E4E9";
			break;
		case "evening":
			color = "#D5BCBA";
			break;
		case "night":
			color = "#12262A";
			break;
	}

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css);
	return `<svg viewBox="${"0 0 1412 289"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-gm69cn"}"><path d="${"M132.873 91.4783C132.873 91.4783 55.3632 236.986 0 289H1411.5L1110\n    124.5L834.5 76.5L641.5 0L412.782 45.7301C349.277 64.468 132.873 91.4783\n    132.873 91.4783Z"}"${add_attribute("fill", color, 0)}></path></svg>`;
});

/* src/components/Hero/Background/SVG/FrontMountain.svelte generated by Svelte v3.24.0 */

const css$1 = {
	code: "svg.svelte-1n305uu{position:absolute;bottom:0;left:0%;height:45%;--hide-mobile:var(--media-lte-sm) none;display:var(--hide-mobile, initial)}",
	map: "{\"version\":3,\"file\":\"FrontMountain.svelte\",\"sources\":[\"FrontMountain.svelte\"],\"sourcesContent\":[\"<script>\\nexport let type = \\\"morning\\\";\\nlet color;\\n\\nswitch (type) {\\n  case \\\"morning\\\":\\n    color = \\\"#D5E2E4\\\";\\n    break;\\n  case \\\"evening\\\":\\n    color = \\\"#F5E6D4\\\";\\n    break;\\n  case \\\"night\\\":\\n    color = \\\"#D5E2E4\\\";\\n    break;\\n\\n  default:\\n    break;\\n}\\n</script>\\n\\n<style>\\nsvg {\\n  position: absolute;\\n  bottom: 0;\\n  left: 0%;\\n\\n  height: 45%;\\n\\n  --hide-mobile: var(--media-lte-sm) none;\\n  display: var(--hide-mobile, initial);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 910 535\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    d=\\\"M96.5 210.5C96.5 210.5 40.2079 449.549 0 535H910L724.63 410.804L581.832\\n    318.452L404.444 0L299.786 135.342C253.665 166.126 96.5 210.5 96.5 210.5Z\\\"\\n    fill={color} />\\n  <path\\n    opacity=\\\"0.1\\\"\\n    d=\\\"M408.49 230.931L479 137L431.302 230.931L278.357 345.101L255.027\\n    534H170L242.065 345.101L408.49 230.931Z\\\"\\n    fill=\\\"black\\\" />\\n  <path\\n    d=\\\"M509.5 418L576 312L530 418L576 496L615 535H576L530 496L509.5 418Z\\\"\\n    fill=\\\"#C0CBCD\\\" />\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAqBA,GAAG,eAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,CAAC,CACT,IAAI,CAAE,EAAE,CAER,MAAM,CAAE,GAAG,CAEX,aAAa,CAAE,wBAAwB,CACvC,OAAO,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,AACtC,CAAC\"}"
};

const FrontMountain = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type = "morning" } = $$props;
	let color;

	switch (type) {
		case "morning":
			color = "#D5E2E4";
			break;
		case "evening":
			color = "#F5E6D4";
			break;
		case "night":
			color = "#D5E2E4";
			break;
	}

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css$1);
	return `<svg viewBox="${"0 0 910 535"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-1n305uu"}"><path d="${"M96.5 210.5C96.5 210.5 40.2079 449.549 0 535H910L724.63 410.804L581.832\n    318.452L404.444 0L299.786 135.342C253.665 166.126 96.5 210.5 96.5 210.5Z"}"${add_attribute("fill", color, 0)}></path><path opacity="${"0.1"}" d="${"M408.49 230.931L479 137L431.302 230.931L278.357 345.101L255.027\n    534H170L242.065 345.101L408.49 230.931Z"}" fill="${"black"}"></path><path d="${"M509.5 418L576 312L530 418L576 496L615 535H576L530 496L509.5 418Z"}" fill="${"#C0CBCD"}"></path></svg>`;
});

/* src/components/Hero/Background/SVG/MidMountain.svelte generated by Svelte v3.24.0 */

const css$2 = {
	code: "svg.svelte-1n9lvnt{position:absolute;bottom:0;--center-mobile:var(--media-lte-sm) 50%;left:var(--center-mobile, 20%);right:var(--center-mobile, initial);--translate-mobile:var(--media-lte-sm) -50%;transform:translateX(var(--translate-mobile, initial));--height:var(--media-lte-sm) 80%;height:var(--height, 60%)}",
	map: "{\"version\":3,\"file\":\"MidMountain.svelte\",\"sources\":[\"MidMountain.svelte\"],\"sourcesContent\":[\"<script>\\nexport let type = \\\"morning\\\";\\nlet color;\\n\\nswitch (type) {\\n  case \\\"morning\\\":\\n    color = \\\"#B9D7DB\\\";\\n    break;\\n  case \\\"evening\\\":\\n    color = \\\"#F2DBBF\\\";\\n    break;\\n  case \\\"night\\\":\\n    color = \\\"#F2F5F5\\\";\\n    break;\\n\\n  default:\\n    break;\\n}\\n</script>\\n\\n<style>\\nsvg {\\n  position: absolute;\\n  bottom: 0;\\n  --center-mobile: var(--media-lte-sm) 50%;\\n  left: var(--center-mobile, 20%);\\n  right: var(--center-mobile, initial);\\n  --translate-mobile: var(--media-lte-sm) -50%;\\n  transform: translateX(var(--translate-mobile, initial));\\n\\n  --height: var(--media-lte-sm) 80%;\\n  height: var(--height, 60%);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 1253 646\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    d=\\\"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\\n    490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873 240.924\\n    132.873 240.924Z\\\"\\n    fill={color} />\\n  <mask\\n    id=\\\"mask0\\\"\\n    mask-type=\\\"alpha\\\"\\n    maskUnits=\\\"userSpaceOnUse\\\"\\n    x=\\\"0\\\"\\n    y=\\\"0\\\"\\n    width=\\\"1253\\\"\\n    height=\\\"646\\\">\\n    <path\\n      d=\\\"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\\n      490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873\\n      240.924 132.873 240.924Z\\\"\\n      fill=\\\"#B9D7DB\\\" />\\n  </mask>\\n  <g mask=\\\"url(#mask0)\\\">\\n    <path\\n      opacity=\\\"0.1\\\"\\n      d=\\\"M751.669 245.016L711.809 157L733.011 254.713L739.372 313.639L742.753\\n      521L875.809 649H929.809L778.809 521L760.998 294.94L751.669 245.016Z\\\"\\n      fill=\\\"black\\\" />\\n    <path\\n      opacity=\\\"0.05\\\"\\n      d=\\\"M345.918 617.142L289.207 660.194L357.029 635.279L395.231 612.383L509.48\\n      613.488L669.807 414L499.932 590.006L380.419 598.519L345.918 617.142Z\\\"\\n      fill=\\\"black\\\" />\\n    <path\\n      d=\\\"M413 41.5222L522.5 94.8728H584.5H630L716.5 77.3062L785 -17.684L611.5\\n      -140L502 -100.963L413 41.5222Z\\\"\\n      fill=\\\"white\\\" />\\n  </g>\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAqBA,GAAG,eAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,CAAC,CACT,eAAe,CAAE,uBAAuB,CACxC,IAAI,CAAE,IAAI,eAAe,CAAC,IAAI,CAAC,CAC/B,KAAK,CAAE,IAAI,eAAe,CAAC,QAAQ,CAAC,CACpC,kBAAkB,CAAE,wBAAwB,CAC5C,SAAS,CAAE,WAAW,IAAI,kBAAkB,CAAC,QAAQ,CAAC,CAAC,CAEvD,QAAQ,CAAE,uBAAuB,CACjC,MAAM,CAAE,IAAI,QAAQ,CAAC,IAAI,CAAC,AAC5B,CAAC\"}"
};

const MidMountain = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type = "morning" } = $$props;
	let color;

	switch (type) {
		case "morning":
			color = "#B9D7DB";
			break;
		case "evening":
			color = "#F2DBBF";
			break;
		case "night":
			color = "#F2F5F5";
			break;
	}

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css$2);
	return `<svg viewBox="${"0 0 1253 646"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-1n9lvnt"}"><path d="${"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\n    490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873 240.924\n    132.873 240.924Z"}"${add_attribute("fill", color, 0)}></path><mask id="${"mask0"}" mask-type="${"alpha"}" maskUnits="${"userSpaceOnUse"}" x="${"0"}" y="${"0"}" width="${"1253"}" height="${"646"}"><path d="${"M132.873 240.924C132.873 240.924 55.3632 539.33 0 646H1253L997.759\n      490.964L770 240.924L599.5 0L412.782 147.104C349.277 185.531 132.873\n      240.924 132.873 240.924Z"}" fill="${"#B9D7DB"}"></path></mask><g mask="${"url(#mask0)"}"><path opacity="${"0.1"}" d="${"M751.669 245.016L711.809 157L733.011 254.713L739.372 313.639L742.753\n      521L875.809 649H929.809L778.809 521L760.998 294.94L751.669 245.016Z"}" fill="${"black"}"></path><path opacity="${"0.05"}" d="${"M345.918 617.142L289.207 660.194L357.029 635.279L395.231 612.383L509.48\n      613.488L669.807 414L499.932 590.006L380.419 598.519L345.918 617.142Z"}" fill="${"black"}"></path><path d="${"M413 41.5222L522.5 94.8728H584.5H630L716.5 77.3062L785 -17.684L611.5\n      -140L502 -100.963L413 41.5222Z"}" fill="${"white"}"></path></g></svg>`;
});

/* src/components/Hero/Background/SVG/Bears.svelte generated by Svelte v3.24.0 */

const css$3 = {
	code: ".bears-normal.svelte-1764xpx{width:92px;height:44px;position:absolute;bottom:-11px;left:15%;transform:scale(1.1)}",
	map: "{\"version\":3,\"file\":\"Bears.svelte\",\"sources\":[\"Bears.svelte\"],\"sourcesContent\":[\"<style>\\n.bears-normal {\\n  width: 92px;\\n  height: 44px;\\n  position: absolute;\\n  bottom: -11px;\\n  left: 15%;\\n  transform: scale(1.1);\\n}</style>\\n\\n<svg width=\\\"92\\\" height=\\\"22\\\" class=\\\"bears-normal\\\" viewBox=\\\"0 0 92 22\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n<path d=\\\"M59.1117 0L78.676 2.11327L87.9314 7.4133L88.4841 8.46383L91.4499 9.98178C91.4499 9.98178 91.0099 13.1654 86.9906 12.1148L80.4391 9.95742L74.5988 13.8933L72.1674 21.8028H69.0142L69.0127 13.8859H58.005L55.6268 21.8028H52.4736V10.0689L59.1117 0Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M80.0586 11.2015L76.4883 16.3597L78.466 21.8027H81.6618L80.0586 11.2015Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M61.2466 18.7285L64.4774 14.493L65.6391 21.8026H62.4311L61.2466 18.7285Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M4.76821 6.31155L18.8214 7.82954L25.4696 11.6366L25.8666 12.3912L27.9971 13.4816C27.9971 13.4816 27.681 15.7684 24.7939 15.0138L20.0879 13.4641L15.8927 16.2912L14.1462 21.9727H11.8813L11.8802 16.2859H3.9732L2.26492 21.9727H0V13.5441L4.76821 6.31155Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M19.8146 14.3582L17.25 18.0633L18.6706 21.9732H20.9662L19.8146 14.3582Z\\\" fill=\\\"#7B5855\\\"/>\\n<path d=\\\"M6.30127 19.7641L8.62199 16.7216L9.45645 21.9722H7.15213L6.30127 19.7641Z\\\" fill=\\\"#7B5855\\\"/>\\n</svg>\\n\\n\"],\"names\":[],\"mappings\":\"AACA,aAAa,eAAC,CAAC,AACb,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,IAAI,CACZ,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,KAAK,CACb,IAAI,CAAE,GAAG,CACT,SAAS,CAAE,MAAM,GAAG,CAAC,AACvB,CAAC\"}"
};

const Bears = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$3);
	return `<svg width="${"92"}" height="${"22"}" class="${"bears-normal svelte-1764xpx"}" viewBox="${"0 0 92 22"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}"><path d="${"M59.1117 0L78.676 2.11327L87.9314 7.4133L88.4841 8.46383L91.4499 9.98178C91.4499 9.98178 91.0099 13.1654 86.9906 12.1148L80.4391 9.95742L74.5988 13.8933L72.1674 21.8028H69.0142L69.0127 13.8859H58.005L55.6268 21.8028H52.4736V10.0689L59.1117 0Z"}" fill="${"#7B5855"}"></path><path d="${"M80.0586 11.2015L76.4883 16.3597L78.466 21.8027H81.6618L80.0586 11.2015Z"}" fill="${"#7B5855"}"></path><path d="${"M61.2466 18.7285L64.4774 14.493L65.6391 21.8026H62.4311L61.2466 18.7285Z"}" fill="${"#7B5855"}"></path><path d="${"M4.76821 6.31155L18.8214 7.82954L25.4696 11.6366L25.8666 12.3912L27.9971 13.4816C27.9971 13.4816 27.681 15.7684 24.7939 15.0138L20.0879 13.4641L15.8927 16.2912L14.1462 21.9727H11.8813L11.8802 16.2859H3.9732L2.26492 21.9727H0V13.5441L4.76821 6.31155Z"}" fill="${"#7B5855"}"></path><path d="${"M19.8146 14.3582L17.25 18.0633L18.6706 21.9732H20.9662L19.8146 14.3582Z"}" fill="${"#7B5855"}"></path><path d="${"M6.30127 19.7641L8.62199 16.7216L9.45645 21.9722H7.15213L6.30127 19.7641Z"}" fill="${"#7B5855"}"></path></svg>`;
});

/* src/components/Hero/Background/SVG/Reflection.svelte generated by Svelte v3.24.0 */

const css$4 = {
	code: "svg.svelte-icy12y{position:absolute;bottom:-20%;left:20%;height:25%;--hide-mobile:var(--media-lte-sm) none;display:var(--hide-mobile, initial)}",
	map: "{\"version\":3,\"file\":\"Reflection.svelte\",\"sources\":[\"Reflection.svelte\"],\"sourcesContent\":[\"<style>\\nsvg {\\n  position: absolute;\\n  bottom: -20%;\\n  left: 20%;\\n\\n  height: 25%;\\n\\n  --hide-mobile: var(--media-lte-sm) none;\\n  display: var(--hide-mobile, initial);\\n}</style>\\n\\n<svg viewBox=\\\"0 0 1412 178\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\">\\n  <path\\n    opacity=\\\"0.1\\\"\\n    d=\\\"M1279.08 120.98C1355.41 88.45 1356.62 31.8581 1412\\n    0.00012207L-0.000106509 -1.37066e-06C-0.000106509 -1.37066e-06 174.204\\n    74.9833 301.607 100.755C405.341 121.738 472.521 111.018 577.204\\n    130.154C654.919 144.361 689.633 171.697 770.273 177.01C860.87 182.979\\n    935.545 160.477 999.072 149.001C1062.6 137.524 1188.14 159.738 1279.08\\n    120.98Z\\\"\\n    fill=\\\"#C1DADF\\\" />\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AACA,GAAG,cAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,MAAM,CAAE,IAAI,CACZ,IAAI,CAAE,GAAG,CAET,MAAM,CAAE,GAAG,CAEX,aAAa,CAAE,wBAAwB,CACvC,OAAO,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,AACtC,CAAC\"}"
};

const Reflection = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$4);
	return `<svg viewBox="${"0 0 1412 178"}" fill="${"none"}" xmlns="${"http://www.w3.org/2000/svg"}" class="${"svelte-icy12y"}"><path opacity="${"0.1"}" d="${"M1279.08 120.98C1355.41 88.45 1356.62 31.8581 1412\n    0.00012207L-0.000106509 -1.37066e-06C-0.000106509 -1.37066e-06 174.204\n    74.9833 301.607 100.755C405.341 121.738 472.521 111.018 577.204\n    130.154C654.919 144.361 689.633 171.697 770.273 177.01C860.87 182.979\n    935.545 160.477 999.072 149.001C1062.6 137.524 1188.14 159.738 1279.08\n    120.98Z"}" fill="${"#C1DADF"}"></path></svg>`;
});

/* src/components/Hero/Background/SVG/MorningSun.svelte generated by Svelte v3.24.0 */

const css$5 = {
	code: "img.svelte-76ztoc{position:absolute;--moon-display:var(--media-lte-sm) none;display:var(--moon-display, initial);top:55%;right:5%;height:275px}",
	map: "{\"version\":3,\"file\":\"MorningSun.svelte\",\"sources\":[\"MorningSun.svelte\"],\"sourcesContent\":[\"<style>\\nimg {\\n  position: absolute;\\n  --moon-display: var(--media-lte-sm) none;\\n  display: var(--moon-display, initial);\\n  top: 55%;\\n  right: 5%;\\n  height: 275px;\\n}</style>\\n\\n<img src=\\\"/dist/static/images/morning-sun.svg\\\" alt=\\\"A moon\\\" />\\n\"],\"names\":[],\"mappings\":\"AACA,GAAG,cAAC,CAAC,AACH,QAAQ,CAAE,QAAQ,CAClB,cAAc,CAAE,wBAAwB,CACxC,OAAO,CAAE,IAAI,cAAc,CAAC,QAAQ,CAAC,CACrC,GAAG,CAAE,GAAG,CACR,KAAK,CAAE,EAAE,CACT,MAAM,CAAE,KAAK,AACf,CAAC\"}"
};

const MorningSun = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$5);
	return `<img src="${"/dist/static/images/morning-sun.svg"}" alt="${"A moon"}" class="${"svelte-76ztoc"}">`;
});

/* src/components/Hero/Background/Background.svelte generated by Svelte v3.24.0 */

const css$6 = {
	code: ".container.svelte-spzizf{overflow:hidden;position:absolute;top:0;bottom:0;left:0;right:0;z-index:-1;background:#d6f1f5}",
	map: "{\"version\":3,\"file\":\"Background.svelte\",\"sources\":[\"Background.svelte\"],\"sourcesContent\":[\"<script>\\nimport {\\n  BackMountain,\\n  MidMountain,\\n  FrontMountain,\\n  Reflection,\\n  Bears,\\n  MorningSun,\\n} from \\\"./SVG/\\\";\\n</script>\\n\\n<style>\\n.container {\\n  overflow: hidden;\\n  position: absolute;\\n  top: 0;\\n  bottom: 0;\\n  left: 0;\\n  right: 0;\\n  z-index: -1;\\n\\n  background: #d6f1f5;\\n}</style>\\n\\n<div class=\\\"container\\\">\\n  <MorningSun />\\n  <BackMountain type=\\\"morning\\\" />\\n  <MidMountain type=\\\"morning\\\" />\\n  <FrontMountain type=\\\"morning\\\" />\\n  <Bears />\\n  <Reflection />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAYA,UAAU,cAAC,CAAC,AACV,QAAQ,CAAE,MAAM,CAChB,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,CAAC,CACN,MAAM,CAAE,CAAC,CACT,IAAI,CAAE,CAAC,CACP,KAAK,CAAE,CAAC,CACR,OAAO,CAAE,EAAE,CAEX,UAAU,CAAE,OAAO,AACrB,CAAC\"}"
};

const Background = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$6);

	return `<div class="${"container svelte-spzizf"}">${validate_component(MorningSun, "MorningSun").$$render($$result, {}, {}, {})}
  ${validate_component(BackMountain, "BackMountain").$$render($$result, { type: "morning" }, {}, {})}
  ${validate_component(MidMountain, "MidMountain").$$render($$result, { type: "morning" }, {}, {})}
  ${validate_component(FrontMountain, "FrontMountain").$$render($$result, { type: "morning" }, {}, {})}
  ${validate_component(Bears, "Bears").$$render($$result, {}, {}, {})}
  ${validate_component(Reflection, "Reflection").$$render($$result, {}, {}, {})}</div>`;
});

/* src/components/Hero/Info.svelte generated by Svelte v3.24.0 */

const css$7 = {
	code: ".info.svelte-1gnpq5v{display:grid;grid-gap:12px;--columns-small:var(--media-lte-sm) 2fr 3fr;grid-template-columns:var(--columns-small, 1fr);--small-placement:var(--media-lte-sm) start end;place-items:var(--small-placement, start)}time.svelte-1gnpq5v{line-height:105%;--small:var(--media-lte-sm) 40px;display:grid;--small-placement:var(--media-lte-sm) end;place-items:var(--small-placement, center start);--small:var(--media-lte-sm) 50px;font-size:var(--small, 73px)}span.svelte-1gnpq5v{--align-text-mobile:var(--media-lte-sm) right;text-align:var(--align-text-mobile, initial)}.sub.svelte-1gnpq5v{--small:var(--media-lte-sm) 33px;font-size:var(--small, 40px);--small-line:var(--media-lte-sm) 100%;line-height:var(--small-line, 105%);display:grid;--small-placement:var(--media-lte-sm) left;text-align:var(--small-placement, left);--small-width:var(--media-lte-sm) 250px;max-width:var(--small-width, 300px)}",
	map: "{\"version\":3,\"file\":\"Info.svelte\",\"sources\":[\"Info.svelte\"],\"sourcesContent\":[\"<style>\\n.info {\\n  display: grid;\\n  grid-gap: 12px;\\n\\n  --columns-small: var(--media-lte-sm) 2fr 3fr;\\n  grid-template-columns: var(--columns-small, 1fr);\\n\\n  --small-placement: var(--media-lte-sm) start end;\\n  place-items: var(--small-placement, start);\\n}\\ntime {\\n  line-height: 105%;\\n  --small: var(--media-lte-sm) 40px;\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) end;\\n  place-items: var(--small-placement, center start);\\n  --small: var(--media-lte-sm) 50px;\\n  font-size: var(--small, 73px);\\n}\\nspan {\\n  --align-text-mobile: var(--media-lte-sm) right;\\n  text-align: var(--align-text-mobile, initial);\\n}\\n.sub {\\n  --small: var(--media-lte-sm) 33px;\\n  font-size: var(--small, 40px);\\n\\n  --small-line: var(--media-lte-sm) 100%;\\n  line-height: var(--small-line, 105%);\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) left;\\n  text-align: var(--small-placement, left);\\n\\n  --small-width: var(--media-lte-sm) 250px;\\n  max-width: var(--small-width, 300px);\\n}</style>\\n\\n<div class=\\\"info\\\">\\n  <time class=\\\"display\\\" datetime=\\\"2020-10-18\\\">\\n    <span>OCT 18</span>\\n    <span>2020</span>\\n  </time>\\n  <div class=\\\"sub display\\\">THE 2ND VIRTUAL CONFERENCE ABOUT SVELTE</div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,KAAK,eAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CAEd,eAAe,CAAE,2BAA2B,CAC5C,qBAAqB,CAAE,IAAI,eAAe,CAAC,IAAI,CAAC,CAEhD,iBAAiB,CAAE,6BAA6B,CAChD,WAAW,CAAE,IAAI,iBAAiB,CAAC,MAAM,CAAC,AAC5C,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,WAAW,CAAE,IAAI,CACjB,OAAO,CAAE,wBAAwB,CAEjC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,uBAAuB,CAC1C,WAAW,CAAE,IAAI,iBAAiB,CAAC,aAAa,CAAC,CACjD,OAAO,CAAE,wBAAwB,CACjC,SAAS,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC/B,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,mBAAmB,CAAE,yBAAyB,CAC9C,UAAU,CAAE,IAAI,mBAAmB,CAAC,QAAQ,CAAC,AAC/C,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,OAAO,CAAE,wBAAwB,CACjC,SAAS,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,CAE7B,YAAY,CAAE,wBAAwB,CACtC,WAAW,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CAEpC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,wBAAwB,CAC3C,UAAU,CAAE,IAAI,iBAAiB,CAAC,KAAK,CAAC,CAExC,aAAa,CAAE,yBAAyB,CACxC,SAAS,CAAE,IAAI,aAAa,CAAC,MAAM,CAAC,AACtC,CAAC\"}"
};

const Info = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$7);

	return `<div class="${"info svelte-1gnpq5v"}"><time class="${"display svelte-1gnpq5v"}" datetime="${"2020-10-18"}"><span class="${"svelte-1gnpq5v"}">OCT 18</span>
    <span class="${"svelte-1gnpq5v"}">2020</span></time>
  <div class="${"sub display svelte-1gnpq5v"}">THE 2ND VIRTUAL CONFERENCE ABOUT SVELTE</div></div>`;
});

/* src/components/Hero/Title.svelte generated by Svelte v3.24.0 */

const css$8 = {
	code: "h1.svelte-16fjkkh{-webkit-margin-before:0;margin-block-start:0;-webkit-margin-after:0;margin-block-end:0;--small-margin:var(--media-lte-sm) 0px;margin-top:var(--small-margin, 155px);display:grid;--small-placement:var(--media-lte-sm) center;place-items:var(--small-placement, center end)}.leading.svelte-16fjkkh{color:var(--background-darkest)}.lagging.svelte-16fjkkh{color:var(--background)}",
	map: "{\"version\":3,\"file\":\"Title.svelte\",\"sources\":[\"Title.svelte\"],\"sourcesContent\":[\"<style>\\nh1 {\\n  -webkit-margin-before: 0;\\n          margin-block-start: 0;\\n  -webkit-margin-after: 0;\\n          margin-block-end: 0;\\n  --small-margin: var(--media-lte-sm) 0px;\\n  margin-top: var(--small-margin, 155px);\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) center;\\n  place-items: var(--small-placement, center end);\\n}\\n.leading {\\n  color: var(--background-darkest);\\n}\\n.lagging {\\n  color: var(--background);\\n}</style>\\n\\n<h1 class=\\\"display\\\">\\n  <span class=\\\"leading\\\">SVELTE</span>\\n  <span class=\\\"lagging\\\">SUMMIT</span>\\n</h1>\\n\"],\"names\":[],\"mappings\":\"AACA,EAAE,eAAC,CAAC,AACF,qBAAqB,CAAE,CAAC,CAChB,kBAAkB,CAAE,CAAC,CAC7B,oBAAoB,CAAE,CAAC,CACf,gBAAgB,CAAE,CAAC,CAC3B,cAAc,CAAE,uBAAuB,CACvC,UAAU,CAAE,IAAI,cAAc,CAAC,MAAM,CAAC,CAEtC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,0BAA0B,CAC7C,WAAW,CAAE,IAAI,iBAAiB,CAAC,WAAW,CAAC,AACjD,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,KAAK,CAAE,IAAI,oBAAoB,CAAC,AAClC,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,KAAK,CAAE,IAAI,YAAY,CAAC,AAC1B,CAAC\"}"
};

const Title = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$8);

	return `<h1 class="${"display svelte-16fjkkh"}"><span class="${"leading svelte-16fjkkh"}">SVELTE</span>
  <span class="${"lagging svelte-16fjkkh"}">SUMMIT</span></h1>`;
});

/* src/components/Hero/Hero.svelte generated by Svelte v3.24.0 */

const css$9 = {
	code: ".container.svelte-1a5c3ok{position:relative;z-index:1001;--small-padding:var(--media-lte-sm) 43px;padding-bottom:var(--small-padding, 125px);display:grid;--small-gap:var(--media-lte-sm) 42px;--medium-gap:var(--media-md) 42px;grid-gap:var(--small-gap, var(--medium-gap, 82px));place-items:start center}.logo.svelte-1a5c3ok{display:grid;place-items:center;--small-padding:var(--media-lte-sm) 43px;padding-top:var(--small-padding, 125px);--small:var(--media-lte-sm) 21px;grid-gap:var(--small, 34px)}img.svelte-1a5c3ok{--small:var(--media-lte-sm) 65px;height:var(--small, 85px);width:var(--small, 85px)}.present.svelte-1a5c3ok{font-size:14px;line-height:150%;letter-spacing:0.5em;text-transform:uppercase;color:#38332d}.text.svelte-1a5c3ok{display:grid;--columns-small:var(--media-lte-sm) 1fr;grid-template-columns:var(--columns-small, auto auto);--small-gap:var(--media-lte-sm) 30px;grid-gap:var(--small-gap, 40px);--mobile-justify:var(--media-lte-sm);justify-self:var(--small-gap, end);--mobile-margin-offset:var(--media-lte-sm) 0;margin-right:var(--mobile-margin-offset, 15vw);padding:0 20px;place-items:start center;color:var(--background);line-height:125%}",
	map: "{\"version\":3,\"file\":\"Hero.svelte\",\"sources\":[\"Hero.svelte\"],\"sourcesContent\":[\"<script>\\nimport { Background } from \\\"./Background/\\\";\\nimport Navigation from \\\"./Navigation.svelte\\\";\\nimport Info from \\\"./Info.svelte\\\";\\nimport Title from \\\"./Title.svelte\\\";\\n\\nconst menu = [\\n  {\\n    name: \\\"Intro\\\",\\n    url: \\\"#intro\\\",\\n  },\\n  {\\n    name: \\\"Sponsors\\\",\\n    url: \\\"#sponsors\\\",\\n  },\\n  {\\n    name: \\\"Speakers\\\",\\n    url: \\\"#speakers\\\",\\n  },\\n  {\\n    name: \\\"FAQ\\\",\\n    url: \\\"#faq\\\",\\n  },\\n];\\n</script>\\n\\n<style>\\n.container {\\n  position: relative;\\n  z-index: 1001;\\n\\n  --small-padding: var(--media-lte-sm) 43px;\\n  padding-bottom: var(--small-padding, 125px);\\n\\n  display: grid;\\n  --small-gap: var(--media-lte-sm) 42px;\\n  --medium-gap: var(--media-md) 42px;\\n  grid-gap: var(--small-gap, var(--medium-gap, 82px));\\n  place-items: start center;\\n}\\n\\n.logo {\\n  display: grid;\\n  place-items: center;\\n  --small-padding: var(--media-lte-sm) 43px;\\n  padding-top: var(--small-padding, 125px);\\n\\n  --small: var(--media-lte-sm) 21px;\\n  grid-gap: var(--small, 34px);\\n}\\n\\nimg {\\n  --small: var(--media-lte-sm) 65px;\\n  height: var(--small, 85px);\\n  width: var(--small, 85px);\\n}\\n\\n.present {\\n  font-size: 14px;\\n  line-height: 150%;\\n  letter-spacing: 0.5em;\\n  text-transform: uppercase;\\n\\n  color: #38332d;\\n}\\n.text {\\n  display: grid;\\n  --columns-small: var(--media-lte-sm) 1fr;\\n  grid-template-columns: var(--columns-small, auto auto);\\n\\n  --small-gap: var(--media-lte-sm) 30px;\\n  grid-gap: var(--small-gap, 40px);\\n\\n  --mobile-justify: var(--media-lte-sm);\\n  justify-self: var(--small-gap, end);\\n\\n  --mobile-margin-offset: var(--media-lte-sm) 0;\\n  margin-right: var(--mobile-margin-offset, 15vw);\\n\\n  padding: 0 20px;\\n\\n  place-items: start center;\\n  color: var(--background);\\n  line-height: 125%;\\n}</style>\\n\\n<div class=\\\"container\\\" id=\\\"intro\\\">\\n  <div class=\\\"ejs-component\\\" data-ejs-component=\\\"Navigation\\\" data-ejs-props={JSON.stringify({ preload: true, loading: 'eager', menu })} data-ejs-options={JSON.stringify({\\\"loading\\\":\\\"lazy\\\"})} />\\n  <div class=\\\"logo\\\">\\n    <a href=\\\"https://sveltesociety.dev/\\\"><img\\n        src=\\\"/dist/static/images/svelte-society-logo.svg\\\"\\n        alt=\\\"Svelte Society\\\" /></a>\\n    <span class=\\\"present\\\">presents</span>\\n  </div>\\n  <div class=\\\"text\\\">\\n    <Title />\\n    <Info />\\n  </div>\\n  <Background />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AA2BA,UAAU,eAAC,CAAC,AACV,QAAQ,CAAE,QAAQ,CAClB,OAAO,CAAE,IAAI,CAEb,eAAe,CAAE,wBAAwB,CACzC,cAAc,CAAE,IAAI,eAAe,CAAC,MAAM,CAAC,CAE3C,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,wBAAwB,CACrC,YAAY,CAAE,oBAAoB,CAClC,QAAQ,CAAE,IAAI,WAAW,CAAC,wBAAwB,CAAC,CACnD,WAAW,CAAE,KAAK,CAAC,MAAM,AAC3B,CAAC,AAED,KAAK,eAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,CACnB,eAAe,CAAE,wBAAwB,CACzC,WAAW,CAAE,IAAI,eAAe,CAAC,MAAM,CAAC,CAExC,OAAO,CAAE,wBAAwB,CACjC,QAAQ,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC9B,CAAC,AAED,GAAG,eAAC,CAAC,AACH,OAAO,CAAE,wBAAwB,CACjC,MAAM,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,CAC1B,KAAK,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC3B,CAAC,AAED,QAAQ,eAAC,CAAC,AACR,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,IAAI,CACjB,cAAc,CAAE,KAAK,CACrB,cAAc,CAAE,SAAS,CAEzB,KAAK,CAAE,OAAO,AAChB,CAAC,AACD,KAAK,eAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,uBAAuB,CACxC,qBAAqB,CAAE,IAAI,eAAe,CAAC,UAAU,CAAC,CAEtD,WAAW,CAAE,wBAAwB,CACrC,QAAQ,CAAE,IAAI,WAAW,CAAC,KAAK,CAAC,CAEhC,gBAAgB,CAAE,mBAAmB,CACrC,YAAY,CAAE,IAAI,WAAW,CAAC,IAAI,CAAC,CAEnC,sBAAsB,CAAE,qBAAqB,CAC7C,YAAY,CAAE,IAAI,sBAAsB,CAAC,KAAK,CAAC,CAE/C,OAAO,CAAE,CAAC,CAAC,IAAI,CAEf,WAAW,CAAE,KAAK,CAAC,MAAM,CACzB,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,WAAW,CAAE,IAAI,AACnB,CAAC\"}"
};

const Hero = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	const menu = [
		{ name: "Intro", url: "#intro" },
		{ name: "Sponsors", url: "#sponsors" },
		{ name: "Speakers", url: "#speakers" },
		{ name: "FAQ", url: "#faq" }
	];

	$$result.css.add(css$9);

	return `<div class="${"container svelte-1a5c3ok"}" id="${"intro"}"><div class="${"ejs-component"}" data-ejs-component="${"Navigation"}"${add_attribute("data-ejs-props", JSON.stringify({ preload: true, loading: "eager", menu }), 0)}${add_attribute("data-ejs-options", JSON.stringify({ "loading": "lazy" }), 0)}></div>
  <div class="${"logo svelte-1a5c3ok"}"><a href="${"https://sveltesociety.dev/"}"><img src="${"/dist/static/images/svelte-society-logo.svg"}" alt="${"Svelte Society"}" class="${"svelte-1a5c3ok"}"></a>
    <span class="${"present svelte-1a5c3ok"}">presents</span></div>
  <div class="${"text svelte-1a5c3ok"}">${validate_component(Title, "Title").$$render($$result, {}, {}, {})}
    ${validate_component(Info, "Info").$$render($$result, {}, {}, {})}</div>
  ${validate_component(Background, "Background").$$render($$result, {}, {}, {})}</div>`;
});

/* src/components/Question.svelte generated by Svelte v3.24.0 */

const css$a = {
	code: "p.svelte-1rfnfjp{color:var(--sky-blue);font-size:16px;--small-font-size:var(--media-lte-sm) 14px}.container.svelte-1rfnfjp{min-width:0}",
	map: "{\"version\":3,\"file\":\"Question.svelte\",\"sources\":[\"Question.svelte\"],\"sourcesContent\":[\"<script>\\nexport let title;\\n</script>\\n\\n<style>\\np {\\n  color: var(--sky-blue);\\n  font-size: 16px;\\n  --small-font-size: var(--media-lte-sm) 14px;\\n}\\n.container {\\n  min-width: 0;\\n}</style>\\n\\n<div class=\\\"container\\\">\\n  <h3>{title}</h3>\\n  <p>\\n    <slot />\\n  </p>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAKA,CAAC,eAAC,CAAC,AACD,KAAK,CAAE,IAAI,UAAU,CAAC,CACtB,SAAS,CAAE,IAAI,CACf,iBAAiB,CAAE,wBAAwB,AAC7C,CAAC,AACD,UAAU,eAAC,CAAC,AACV,SAAS,CAAE,CAAC,AACd,CAAC\"}"
};

const Question = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { title } = $$props;
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	$$result.css.add(css$a);

	return `<div class="${"container svelte-1rfnfjp"}"><h3>${escape(title)}</h3>
  <p class="${"svelte-1rfnfjp"}">${$$slots.default ? $$slots.default({}) : ``}</p></div>`;
});

/* src/components/Sections/Sponsors.svelte generated by Svelte v3.24.0 */

const css$b = {
	code: ".background.svelte-1tp73ch.svelte-1tp73ch{--small-padding:var(--media-lte-sm) 50px;padding:var(--small-padding, 200px 40px 50px 40px);background:#2b636c;background-image:url(/dist/static/images/lake.svg);background-position:top;background-repeat:no-repeat;--mobile-backgrounds:var(--media-lte-sm) auto 130px;background-size:var(--mobile-backgrounds, auto 150px)}.container.svelte-1tp73ch.svelte-1tp73ch{display:grid;--small-grid:var(--media-lte-sm) 0;grid-gap:var(--small-grid, 30px);max-width:var(--container-width);--small-margin:var(--media-lte-sm) 0px 20px -50px 20px;margin:var(--small-margin, -120px auto 70px auto);--small-padding:var(--media-lte-sm) 50px 0;padding:var(--small-padding, initial)}h2.svelte-1tp73ch.svelte-1tp73ch{--small-font:var(--media-lte-sm) 34px;font-size:var(--small-font, 60px);font-family:\"Anton\";line-height:150%;text-align:center}.sponsors.svelte-1tp73ch.svelte-1tp73ch{width:100%;display:grid;grid-gap:43px}.sponsors+.sponsors.svelte-1tp73ch.svelte-1tp73ch{--small-top:var(--media-lte-sm) 40px;margin-top:var(--small-top, 0)}.gold.svelte-1tp73ch.svelte-1tp73ch{grid-template-columns:repeat(auto-fit, minmax(300px, 1fr))}.silver.svelte-1tp73ch.svelte-1tp73ch{grid-template-columns:repeat(auto-fit, minmax(150px, 1fr))}.sponsor.svelte-1tp73ch.svelte-1tp73ch{display:grid;justify-content:center;align-items:center;background:#1c464d;padding:30px 50px}.sponsor.svelte-1tp73ch span.svelte-1tp73ch{color:#e4eef0;font-size:18px;opacity:0.5}.silver.sponsors.svelte-1tp73ch .sponsor.svelte-1tp73ch{padding:20px 40px}.silver.sponsors.svelte-1tp73ch span.svelte-1tp73ch{font-size:16px}.gold.svelte-1tp73ch img.svelte-1tp73ch{height:66px;max-height:66px}.silver.svelte-1tp73ch img.svelte-1tp73ch{height:50px;max-height:50px}.info.svelte-1tp73ch.svelte-1tp73ch{margin:0 auto;margin-top:40px;max-width:575px;text-align:center}[data-tooltip].svelte-1tp73ch.svelte-1tp73ch{position:relative}[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:before,[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:after{position:absolute;visibility:hidden;opacity:0;transition:opacity 0.2s ease-in-out, visibility 0.2s ease-in-out,\n    transform 0.2s cubic-bezier(0.71, 1.7, 0.77, 1.24);transform:translate3d(0, 0, 0);pointer-events:none}[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:hover:before,[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:hover:after,[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:focus:before,[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:focus:after{visibility:visible;opacity:1}[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:after{z-index:1000;padding:8px;width:260px;background-color:#000;background-color:hsla(0, 0%, 20%, 0.9);color:#fff;font-weight:normal;content:attr(data-tooltip);font-size:14px;line-height:1.2}[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:before,[data-tooltip].svelte-1tp73ch.svelte-1tp73ch:after{top:100%;--small-adjust:var(--media-lte-sm) calc(50% - 138px);left:var(--small-adjust, calc(70% - 138px))}",
	map: "{\"version\":3,\"file\":\"Sponsors.svelte\",\"sources\":[\"Sponsors.svelte\"],\"sourcesContent\":[\"<style>\\n.background {\\n  --small-padding: var(--media-lte-sm) 50px;\\n  padding: var(--small-padding, 200px 40px 50px 40px);\\n\\n  background: #2b636c;\\n  background-image: url(/dist/static/images/lake.svg);\\n  background-position: top;\\n  background-repeat: no-repeat;\\n\\n  --mobile-backgrounds: var(--media-lte-sm) auto 130px;\\n  background-size: var(--mobile-backgrounds, auto 150px);\\n}\\n.container {\\n  display: grid;\\n  --small-grid: var(--media-lte-sm) 0;\\n  grid-gap: var(--small-grid, 30px);\\n  max-width: var(--container-width);\\n\\n  --small-margin: var(--media-lte-sm) 0px 20px -50px 20px;\\n  margin: var(--small-margin, -120px auto 70px auto);\\n\\n  --small-padding: var(--media-lte-sm) 50px 0;\\n  padding: var(--small-padding, initial);\\n}\\nh2 {\\n  --small-font: var(--media-lte-sm) 34px;\\n  font-size: var(--small-font, 60px);\\n  font-family: \\\"Anton\\\";\\n  line-height: 150%;\\n  text-align: center;\\n}\\n.sponsors {\\n  width: 100%;\\n  display: grid;\\n  grid-gap: 43px;\\n}\\n.sponsors + .sponsors {\\n  --small-top: var(--media-lte-sm) 40px;\\n  margin-top: var(--small-top, 0);\\n}\\n.gold {\\n  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\\n}\\n.silver {\\n  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\\n}\\n.sponsor {\\n  display: grid;\\n  justify-content: center;\\n  align-items: center;\\n  background: #1c464d;\\n  padding: 30px 50px;\\n}\\n.sponsor span {\\n  color: #e4eef0;\\n  font-size: 18px;\\n  opacity: 0.5;\\n}\\n\\n.silver.sponsors .sponsor {\\n  padding: 20px 40px;\\n}\\n\\n.silver.sponsors span {\\n  font-size: 16px;\\n}\\n\\n.gold img {\\n  height: 66px;\\n  max-height: 66px;\\n}\\n\\n.silver img {\\n  height: 50px;\\n  max-height: 50px;\\n}\\n.info {\\n  margin: 0 auto;\\n  margin-top: 40px;\\n  max-width: 575px;\\n  text-align: center;\\n}\\n\\n[data-tooltip] {\\n  position: relative;\\n}\\n\\n[data-tooltip]:before,\\n[data-tooltip]:after {\\n  position: absolute;\\n  visibility: hidden;\\n  opacity: 0;\\n  transition: opacity 0.2s ease-in-out, visibility 0.2s ease-in-out,\\n    transform 0.2s cubic-bezier(0.71, 1.7, 0.77, 1.24);\\n  transform: translate3d(0, 0, 0);\\n  pointer-events: none;\\n}\\n\\n[data-tooltip]:hover:before,\\n[data-tooltip]:hover:after,\\n[data-tooltip]:focus:before,\\n[data-tooltip]:focus:after {\\n  visibility: visible;\\n  opacity: 1;\\n}\\n\\n[data-tooltip]:after {\\n  z-index: 1000;\\n  padding: 8px;\\n  width: 260px;\\n  background-color: #000;\\n  background-color: hsla(0, 0%, 20%, 0.9);\\n  color: #fff;\\n  font-weight: normal;\\n  content: attr(data-tooltip);\\n  font-size: 14px;\\n  line-height: 1.2;\\n}\\n\\n[data-tooltip]:before,\\n[data-tooltip]:after {\\n  top: 100%;\\n\\n  --small-adjust: var(--media-lte-sm) calc(50% - 138px);\\n  left: var(--small-adjust, calc(70% - 138px));\\n}</style>\\n\\n<div class=\\\"background\\\" id=\\\"sponsors\\\">\\n  <div class=\\\"container\\\">\\n    <h2>SPONSORED BY*</h2>\\n    <div class=\\\"gold sponsors\\\">\\n      <a\\n        href=\\\"https://aws.amazon.com/amplify/\\\"\\n        rel=\\\"noopener noreferrer\\\"\\n        target=\\\"_blank\\\"\\n        class=\\\"sponsor\\\"\\n        data-tooltip=\\\"AWS Amplify – The fastest, easiest way to develop mobile and web apps that scale\\\">\\n        <img src=\\\"/dist/static/images/sponsors/aws.svg\\\" alt=\\\"\\\" />\\n      </a>\\n      <a\\n        href=\\\"https://www.coderight.se\\\"\\n        rel=\\\"noopener noreferrer\\\"\\n        target=\\\"_blank\\\"\\n        class=\\\"sponsor\\\">\\n        <img src=\\\"/dist/static/images/sponsors/b3coderight.svg\\\" alt=\\\"\\\" />\\n      </a>\\n      <div class=\\\"sponsor\\\"><span>Sponsor spot open</span></div>\\n    </div>\\n    <div class=\\\"silver sponsors\\\">\\n      <a\\n        href=\\\"https://oasisdigital.com\\\"\\n        rel=\\\"noopener noreferrer\\\"\\n        target=\\\"_blank\\\"\\n        class=\\\"sponsor\\\"\\n        data-tooltip=\\\"Oasis Digital delivers advanced software product development and training services, focused on web technology and full stack solutions.\\\">\\n        <img src=\\\"/dist/static/images/sponsors/oasis.svg\\\" alt=\\\"\\\" />\\n      </a>\\n      <div class=\\\"sponsor\\\"><span>Sponsor spot open</span></div>\\n      <div class=\\\"sponsor\\\"><span>Sponsor spot open</span></div>\\n      <div class=\\\"sponsor\\\"><span>Sponsor spot open</span></div>\\n    </div>\\n    <p class=\\\"info\\\">\\n      *We’re looking for more sponsors for the event. Any financial backing will\\n      be used to support the event and further development of Svelte itself. <a\\n        href=\\\"mailto:sponsors@sveltesociety.dev\\\">Get in touch</a>.\\n    </p>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,WAAW,8BAAC,CAAC,AACX,eAAe,CAAE,wBAAwB,CACzC,OAAO,CAAE,IAAI,eAAe,CAAC,qBAAqB,CAAC,CAEnD,UAAU,CAAE,OAAO,CACnB,gBAAgB,CAAE,IAAI,4BAA4B,CAAC,CACnD,mBAAmB,CAAE,GAAG,CACxB,iBAAiB,CAAE,SAAS,CAE5B,oBAAoB,CAAE,8BAA8B,CACpD,eAAe,CAAE,IAAI,oBAAoB,CAAC,WAAW,CAAC,AACxD,CAAC,AACD,UAAU,8BAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,YAAY,CAAE,qBAAqB,CACnC,QAAQ,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CACjC,SAAS,CAAE,IAAI,iBAAiB,CAAC,CAEjC,cAAc,CAAE,uCAAuC,CACvD,MAAM,CAAE,IAAI,cAAc,CAAC,sBAAsB,CAAC,CAElD,eAAe,CAAE,0BAA0B,CAC3C,OAAO,CAAE,IAAI,eAAe,CAAC,QAAQ,CAAC,AACxC,CAAC,AACD,EAAE,8BAAC,CAAC,AACF,YAAY,CAAE,wBAAwB,CACtC,SAAS,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CAClC,WAAW,CAAE,OAAO,CACpB,WAAW,CAAE,IAAI,CACjB,UAAU,CAAE,MAAM,AACpB,CAAC,AACD,SAAS,8BAAC,CAAC,AACT,KAAK,CAAE,IAAI,CACX,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,AAChB,CAAC,AACD,SAAS,CAAG,SAAS,8BAAC,CAAC,AACrB,WAAW,CAAE,wBAAwB,CACrC,UAAU,CAAE,IAAI,WAAW,CAAC,EAAE,CAAC,AACjC,CAAC,AACD,KAAK,8BAAC,CAAC,AACL,qBAAqB,CAAE,OAAO,QAAQ,CAAC,CAAC,OAAO,KAAK,CAAC,CAAC,GAAG,CAAC,CAAC,AAC7D,CAAC,AACD,OAAO,8BAAC,CAAC,AACP,qBAAqB,CAAE,OAAO,QAAQ,CAAC,CAAC,OAAO,KAAK,CAAC,CAAC,GAAG,CAAC,CAAC,AAC7D,CAAC,AACD,QAAQ,8BAAC,CAAC,AACR,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,MAAM,CACnB,UAAU,CAAE,OAAO,CACnB,OAAO,CAAE,IAAI,CAAC,IAAI,AACpB,CAAC,AACD,uBAAQ,CAAC,IAAI,eAAC,CAAC,AACb,KAAK,CAAE,OAAO,CACd,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,GAAG,AACd,CAAC,AAED,OAAO,wBAAS,CAAC,QAAQ,eAAC,CAAC,AACzB,OAAO,CAAE,IAAI,CAAC,IAAI,AACpB,CAAC,AAED,OAAO,wBAAS,CAAC,IAAI,eAAC,CAAC,AACrB,SAAS,CAAE,IAAI,AACjB,CAAC,AAED,oBAAK,CAAC,GAAG,eAAC,CAAC,AACT,MAAM,CAAE,IAAI,CACZ,UAAU,CAAE,IAAI,AAClB,CAAC,AAED,sBAAO,CAAC,GAAG,eAAC,CAAC,AACX,MAAM,CAAE,IAAI,CACZ,UAAU,CAAE,IAAI,AAClB,CAAC,AACD,KAAK,8BAAC,CAAC,AACL,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,UAAU,CAAE,IAAI,CAChB,SAAS,CAAE,KAAK,CAChB,UAAU,CAAE,MAAM,AACpB,CAAC,AAED,CAAC,YAAY,CAAC,8BAAC,CAAC,AACd,QAAQ,CAAE,QAAQ,AACpB,CAAC,AAED,CAAC,YAAY,+BAAC,OAAO,CACrB,CAAC,YAAY,+BAAC,MAAM,AAAC,CAAC,AACpB,QAAQ,CAAE,QAAQ,CAClB,UAAU,CAAE,MAAM,CAClB,OAAO,CAAE,CAAC,CACV,UAAU,CAAE,OAAO,CAAC,IAAI,CAAC,WAAW,CAAC,CAAC,UAAU,CAAC,IAAI,CAAC,WAAW,CAAC;IAChE,SAAS,CAAC,IAAI,CAAC,aAAa,IAAI,CAAC,CAAC,GAAG,CAAC,CAAC,IAAI,CAAC,CAAC,IAAI,CAAC,CACpD,SAAS,CAAE,YAAY,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAC/B,cAAc,CAAE,IAAI,AACtB,CAAC,AAED,CAAC,YAAY,+BAAC,MAAM,OAAO,CAC3B,CAAC,YAAY,+BAAC,MAAM,MAAM,CAC1B,CAAC,YAAY,+BAAC,MAAM,OAAO,CAC3B,CAAC,YAAY,+BAAC,MAAM,MAAM,AAAC,CAAC,AAC1B,UAAU,CAAE,OAAO,CACnB,OAAO,CAAE,CAAC,AACZ,CAAC,AAED,CAAC,YAAY,+BAAC,MAAM,AAAC,CAAC,AACpB,OAAO,CAAE,IAAI,CACb,OAAO,CAAE,GAAG,CACZ,KAAK,CAAE,KAAK,CACZ,gBAAgB,CAAE,IAAI,CACtB,gBAAgB,CAAE,KAAK,CAAC,CAAC,CAAC,EAAE,CAAC,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,CACvC,KAAK,CAAE,IAAI,CACX,WAAW,CAAE,MAAM,CACnB,OAAO,CAAE,KAAK,YAAY,CAAC,CAC3B,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,GAAG,AAClB,CAAC,AAED,CAAC,YAAY,+BAAC,OAAO,CACrB,CAAC,YAAY,+BAAC,MAAM,AAAC,CAAC,AACpB,GAAG,CAAE,IAAI,CAET,cAAc,CAAE,qCAAqC,CACrD,IAAI,CAAE,IAAI,cAAc,CAAC,kBAAkB,CAAC,AAC9C,CAAC\"}"
};

const Sponsors = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$b);

	return `<div class="${"background svelte-1tp73ch"}" id="${"sponsors"}"><div class="${"container svelte-1tp73ch"}"><h2 class="${"svelte-1tp73ch"}">SPONSORED BY*</h2>
    <div class="${"gold sponsors svelte-1tp73ch"}"><a href="${"https://aws.amazon.com/amplify/"}" rel="${"noopener noreferrer"}" target="${"_blank"}" class="${"sponsor svelte-1tp73ch"}" data-tooltip="${"AWS Amplify – The fastest, easiest way to develop mobile and web apps that scale"}"><img src="${"/dist/static/images/sponsors/aws.svg"}" alt="${""}" class="${"svelte-1tp73ch"}"></a>
      <a href="${"https://www.coderight.se"}" rel="${"noopener noreferrer"}" target="${"_blank"}" class="${"sponsor svelte-1tp73ch"}"><img src="${"/dist/static/images/sponsors/b3coderight.svg"}" alt="${""}" class="${"svelte-1tp73ch"}"></a>
      <div class="${"sponsor svelte-1tp73ch"}"><span class="${"svelte-1tp73ch"}">Sponsor spot open</span></div></div>
    <div class="${"silver sponsors svelte-1tp73ch"}"><a href="${"https://oasisdigital.com"}" rel="${"noopener noreferrer"}" target="${"_blank"}" class="${"sponsor svelte-1tp73ch"}" data-tooltip="${"Oasis Digital delivers advanced software product development and training services, focused on web technology and full stack solutions."}"><img src="${"/dist/static/images/sponsors/oasis.svg"}" alt="${""}" class="${"svelte-1tp73ch"}"></a>
      <div class="${"sponsor svelte-1tp73ch"}"><span class="${"svelte-1tp73ch"}">Sponsor spot open</span></div>
      <div class="${"sponsor svelte-1tp73ch"}"><span class="${"svelte-1tp73ch"}">Sponsor spot open</span></div>
      <div class="${"sponsor svelte-1tp73ch"}"><span class="${"svelte-1tp73ch"}">Sponsor spot open</span></div></div>
    <p class="${"info svelte-1tp73ch"}">*We’re looking for more sponsors for the event. Any financial backing will
      be used to support the event and further development of Svelte itself. <a href="${"mailto:sponsors@sveltesociety.dev"}">Get in touch</a>.
    </p></div></div>`;
});

/* src/components/Speaker.svelte generated by Svelte v3.24.0 */

const css$c = {
	code: ".speaker.svelte-1sfnb0p.svelte-1sfnb0p{display:grid;grid-gap:32px;grid-template-columns:80px auto}.image.svelte-1sfnb0p img.svelte-1sfnb0p{width:80px;height:80px;-o-object-fit:cover;object-fit:cover;-webkit-clip-path:polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);clip-path:polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)}.name.svelte-1sfnb0p.svelte-1sfnb0p{color:#e4eef0;opacity:0.67}h3.svelte-1sfnb0p.svelte-1sfnb0p{font-family:\"Overpass\";margin:0 auto;line-height:140%;padding-top:5px;font-size:2em}a.svelte-1sfnb0p.svelte-1sfnb0p{text-decoration:none}.twitter.svelte-1sfnb0p.svelte-1sfnb0p{display:grid;grid-gap:5px;align-items:center;grid-template-columns:auto 1fr;color:#005daa}.twitter.svelte-1sfnb0p a.svelte-1sfnb0p{color:white;font-size:14px}.twitter.svelte-1sfnb0p img.svelte-1sfnb0p{height:16px}div.svelte-1sfnb0p.svelte-1sfnb0p p{font-size:18px;color:#bedde2;line-height:170%}",
	map: "{\"version\":3,\"file\":\"Speaker.svelte\",\"sources\":[\"Speaker.svelte\"],\"sourcesContent\":[\"<script>\\nexport let link = false;\\nexport let speaker;\\nconst { image, title, name, twitter, twitterUser } = speaker.data;\\n</script>\\n\\n<style>\\n.speaker {\\n  display: grid;\\n  grid-gap: 32px;\\n  grid-template-columns: 80px auto;\\n}\\n.image img {\\n  width: 80px;\\n  height: 80px;\\n  -o-object-fit: cover;\\n     object-fit: cover;\\n  -webkit-clip-path: polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);\\n          clip-path: polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);\\n}\\n.name {\\n  color: #e4eef0;\\n\\n  opacity: 0.67;\\n}\\nh3 {\\n  font-family: \\\"Overpass\\\";\\n  margin: 0 auto;\\n  line-height: 140%;\\n  padding-top: 5px;\\n  font-size: 2em;\\n}\\na {\\n  text-decoration: none;\\n}\\n.twitter {\\n  display: grid;\\n  grid-gap: 5px;\\n  align-items: center;\\n  grid-template-columns: auto 1fr;\\n  color: #005daa;\\n}\\n.twitter a {\\n  color: white;\\n  font-size: 14px;\\n}\\n.twitter img {\\n  height: 16px;\\n}\\ndiv :global(p) {\\n  font-size: 18px;\\n  color: #bedde2;\\n  line-height: 170%;\\n}</style>\\n\\n<div class=\\\"speaker\\\">\\n  <div class=\\\"image\\\">\\n    <img src=\\\"/dist/static/images/speakers/{image}\\\" alt=\\\"Speaker profile\\\" />\\n  </div>\\n  <div>\\n    <span class=\\\"name\\\">{name}</span>\\n    <h3>\\n      {#if link}<a href=\\\"/talks/{speaker.slug}\\\">{title}</a>{:else}{title}{/if}\\n    </h3>\\n    {@html speaker.content}\\n    <div class=\\\"twitter\\\">\\n      <img src=\\\"/dist/static/images/twitter.svg\\\" alt=\\\"Twitter logo\\\" />\\n      <a href={twitter}>{twitterUser}</a>\\n    </div>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAOA,QAAQ,8BAAC,CAAC,AACR,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CACd,qBAAqB,CAAE,IAAI,CAAC,IAAI,AAClC,CAAC,AACD,qBAAM,CAAC,GAAG,eAAC,CAAC,AACV,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,IAAI,CACZ,aAAa,CAAE,KAAK,CACjB,UAAU,CAAE,KAAK,CACpB,iBAAiB,CAAE,QAAQ,GAAG,CAAC,EAAE,CAAC,CAAC,IAAI,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,IAAI,CAAC,CAAC,EAAE,CAAC,GAAG,CAAC,CACtD,SAAS,CAAE,QAAQ,GAAG,CAAC,EAAE,CAAC,CAAC,IAAI,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,IAAI,CAAC,CAAC,EAAE,CAAC,GAAG,CAAC,AAChE,CAAC,AACD,KAAK,8BAAC,CAAC,AACL,KAAK,CAAE,OAAO,CAEd,OAAO,CAAE,IAAI,AACf,CAAC,AACD,EAAE,8BAAC,CAAC,AACF,WAAW,CAAE,UAAU,CACvB,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,WAAW,CAAE,IAAI,CACjB,WAAW,CAAE,GAAG,CAChB,SAAS,CAAE,GAAG,AAChB,CAAC,AACD,CAAC,8BAAC,CAAC,AACD,eAAe,CAAE,IAAI,AACvB,CAAC,AACD,QAAQ,8BAAC,CAAC,AACR,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,GAAG,CACb,WAAW,CAAE,MAAM,CACnB,qBAAqB,CAAE,IAAI,CAAC,GAAG,CAC/B,KAAK,CAAE,OAAO,AAChB,CAAC,AACD,uBAAQ,CAAC,CAAC,eAAC,CAAC,AACV,KAAK,CAAE,KAAK,CACZ,SAAS,CAAE,IAAI,AACjB,CAAC,AACD,uBAAQ,CAAC,GAAG,eAAC,CAAC,AACZ,MAAM,CAAE,IAAI,AACd,CAAC,AACD,iCAAG,CAAC,AAAQ,CAAC,AAAE,CAAC,AACd,SAAS,CAAE,IAAI,CACf,KAAK,CAAE,OAAO,CACd,WAAW,CAAE,IAAI,AACnB,CAAC\"}"
};

const Speaker = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { link = false } = $$props;
	let { speaker } = $$props;
	const { image, title, name, twitter, twitterUser } = speaker.data;
	if ($$props.link === void 0 && $$bindings.link && link !== void 0) $$bindings.link(link);
	if ($$props.speaker === void 0 && $$bindings.speaker && speaker !== void 0) $$bindings.speaker(speaker);
	$$result.css.add(css$c);

	return `<div class="${"speaker svelte-1sfnb0p"}"><div class="${"image svelte-1sfnb0p"}"><img src="${"/dist/static/images/speakers/" + escape(image)}" alt="${"Speaker profile"}" class="${"svelte-1sfnb0p"}"></div>
  <div class="${"svelte-1sfnb0p"}"><span class="${"name svelte-1sfnb0p"}">${escape(name)}</span>
    <h3 class="${"svelte-1sfnb0p"}">${link
	? `<a href="${"/talks/" + escape(speaker.slug)}" class="${"svelte-1sfnb0p"}">${escape(title)}</a>`
	: `${escape(title)}`}</h3>
    ${speaker.content}
    <div class="${"twitter svelte-1sfnb0p"}"><img src="${"/dist/static/images/twitter.svg"}" alt="${"Twitter logo"}" class="${"svelte-1sfnb0p"}">
      <a${add_attribute("href", twitter, 0)} class="${"svelte-1sfnb0p"}">${escape(twitterUser)}</a></div></div></div>`;
});

/* src/components/Sections/Speakers.svelte generated by Svelte v3.24.0 */

const css$d = {
	code: ".shaded.svelte-58fk2l{--small-padding:var(--media-lte-sm) 0 25px 120px 25px;padding:var(--small-padding, 0 40px 170px 40px);background:var(--background);background-image:url(/dist/static/images/forest.svg);background-position:bottom left;background-repeat:repeat-x}section.svelte-58fk2l{display:grid;justify-content:initial;margin:0 auto;--small-padding:var(--media-lte-sm) 50px 0;padding:var(--small-padding, initial 0);max-width:var(--container-width)}.grid.svelte-58fk2l{display:grid;grid-gap:50px;grid-template-columns:repeat(auto-fill, minmax(400px, 1fr))}",
	map: "{\"version\":3,\"file\":\"Speakers.svelte\",\"sources\":[\"Speakers.svelte\"],\"sourcesContent\":[\"<script>\\nexport let talks;\\nimport Speaker from \\\"../Speaker.svelte\\\";\\n</script>\\n\\n<style>\\n.shaded {\\n  --small-padding: var(--media-lte-sm) 0 25px 120px 25px;\\n  padding: var(--small-padding, 0 40px 170px 40px);\\n  background: var(--background);\\n  background-image: url(/dist/static/images/forest.svg);\\n  background-position: bottom left;\\n  background-repeat: repeat-x;\\n}\\nsection {\\n  display: grid;\\n  justify-content: initial;\\n  margin: 0 auto;\\n\\n  --small-padding: var(--media-lte-sm) 50px 0;\\n  padding: var(--small-padding, initial 0);\\n  max-width: var(--container-width);\\n}\\n.grid {\\n  display: grid;\\n  grid-gap: 50px;\\n  grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));\\n}\\n/* @media screen and (max-width: 600px) {\\n  .grid {\\n    grid-template-columns: 1fr;\\n  }\\n} */</style>\\n\\n<div class=\\\"shaded\\\">\\n  <section id=\\\"speakers\\\">\\n    <h2>SPEAKERS</h2>\\n    <div class=\\\"grid\\\">\\n      {#each talks as speaker}\\n        <Speaker {speaker} />\\n      {/each}\\n    </div>\\n  </section>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAMA,OAAO,cAAC,CAAC,AACP,eAAe,CAAE,qCAAqC,CACtD,OAAO,CAAE,IAAI,eAAe,CAAC,kBAAkB,CAAC,CAChD,UAAU,CAAE,IAAI,YAAY,CAAC,CAC7B,gBAAgB,CAAE,IAAI,8BAA8B,CAAC,CACrD,mBAAmB,CAAE,MAAM,CAAC,IAAI,CAChC,iBAAiB,CAAE,QAAQ,AAC7B,CAAC,AACD,OAAO,cAAC,CAAC,AACP,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,OAAO,CACxB,MAAM,CAAE,CAAC,CAAC,IAAI,CAEd,eAAe,CAAE,0BAA0B,CAC3C,OAAO,CAAE,IAAI,eAAe,CAAC,UAAU,CAAC,CACxC,SAAS,CAAE,IAAI,iBAAiB,CAAC,AACnC,CAAC,AACD,KAAK,cAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CACd,qBAAqB,CAAE,OAAO,SAAS,CAAC,CAAC,OAAO,KAAK,CAAC,CAAC,GAAG,CAAC,CAAC,AAC9D,CAAC\"}"
};

const Speakers = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { talks } = $$props;
	if ($$props.talks === void 0 && $$bindings.talks && talks !== void 0) $$bindings.talks(talks);
	$$result.css.add(css$d);

	return `<div class="${"shaded svelte-58fk2l"}"><section id="${"speakers"}" class="${"svelte-58fk2l"}"><h2>SPEAKERS</h2>
    <div class="${"grid svelte-58fk2l"}">${each(talks, speaker => `${validate_component(Speaker, "Speaker").$$render($$result, { speaker }, {}, {})}`)}</div></section></div>`;
});

/* src/components/Sections/FAQ.svelte generated by Svelte v3.24.0 */

const css$e = {
	code: ".background.svelte-1ntitv7{--small-padding:var(--media-lte-sm) 45px 25px;padding:var(--small-padding, 140px 40px);background:var(--background-dark);display:grid;place-items:center}.container.svelte-1ntitv7{max-width:var(--container-width)}.questions.svelte-1ntitv7{display:grid;grid-gap:40px 50px;--small-grid:var(--media-lte-sm) auto;grid-template-columns:repeat(\n    auto-fit,\n    minmax(var(--small-grid, 350px), 1fr)\n  )}",
	map: "{\"version\":3,\"file\":\"FAQ.svelte\",\"sources\":[\"FAQ.svelte\"],\"sourcesContent\":[\"<style>\\n.background {\\n  --small-padding: var(--media-lte-sm) 45px 25px;\\n  padding: var(--small-padding, 140px 40px);\\n\\n  background: var(--background-dark);\\n  display: grid;\\n  place-items: center;\\n}\\n.container {\\n  max-width: var(--container-width);\\n}\\n.questions {\\n  display: grid;\\n  grid-gap: 40px 50px;\\n\\n  --small-grid: var(--media-lte-sm) auto;\\n  grid-template-columns: repeat(\\n    auto-fit,\\n    minmax(var(--small-grid, 350px), 1fr)\\n  );\\n}</style>\\n\\n<div class=\\\"background\\\" id=\\\"faq\\\">\\n  <div class=\\\"container\\\">\\n    <h2>Frequently Asked Questions</h2>\\n    <div class=\\\"questions\\\">\\n      <slot />\\n    </div>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,WAAW,eAAC,CAAC,AACX,eAAe,CAAE,6BAA6B,CAC9C,OAAO,CAAE,IAAI,eAAe,CAAC,WAAW,CAAC,CAEzC,UAAU,CAAE,IAAI,iBAAiB,CAAC,CAClC,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,AACrB,CAAC,AACD,UAAU,eAAC,CAAC,AACV,SAAS,CAAE,IAAI,iBAAiB,CAAC,AACnC,CAAC,AACD,UAAU,eAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CAAC,IAAI,CAEnB,YAAY,CAAE,wBAAwB,CACtC,qBAAqB,CAAE;IACrB,QAAQ,CAAC;IACT,OAAO,IAAI,YAAY,CAAC,MAAM,CAAC,CAAC,CAAC,GAAG,CAAC;GACtC,AACH,CAAC\"}"
};

const FAQ = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$e);

	return `<div class="${"background svelte-1ntitv7"}" id="${"faq"}"><div class="${"container svelte-1ntitv7"}"><h2>Frequently Asked Questions</h2>
    <div class="${"questions svelte-1ntitv7"}">${$$slots.default ? $$slots.default({}) : ``}</div></div></div>`;
});

/* src/components/Sections/Footer.svelte generated by Svelte v3.24.0 */

const css$f = {
	code: ".container.svelte-1vhtiuj{width:calc(100% - 50px);--small-max-width:var(--media-lte-sm) 300px;max-width:var(--small-max-width, var(--container-width));margin:0 auto;opacity:0.5;--small-padding:var(--media-lte-sm) 40px 25px 130px 25px;padding:var(--small-padding, 80px 25px 200px 25px);display:grid;--small-grid:var(--media-lte-sm) auto;grid-template-columns:var(--small-grid, auto auto);--small-justify:var(--media-lte-sm) center;justify-content:var(--small-justify, space-between);--text-center:var(--media-lte-sm) center;text-align:var(--text-center, initial);line-height:200%}.design-by.svelte-1vhtiuj{display:grid;--small-justify:var(--media-lte-sm) center;justify-content:var(--small-justify, end)}",
	map: "{\"version\":3,\"file\":\"Footer.svelte\",\"sources\":[\"Footer.svelte\"],\"sourcesContent\":[\"<style>\\n.container {\\n  width: calc(100% - 50px);\\n  --small-max-width: var(--media-lte-sm) 300px;\\n  max-width: var(--small-max-width, var(--container-width));\\n  margin: 0 auto;\\n  opacity: 0.5;\\n  --small-padding: var(--media-lte-sm) 40px 25px 130px 25px;\\n  padding: var(--small-padding, 80px 25px 200px 25px);\\n\\n  display: grid;\\n  --small-grid: var(--media-lte-sm) auto;\\n  grid-template-columns: var(--small-grid, auto auto);\\n\\n  --small-justify: var(--media-lte-sm) center;\\n  justify-content: var(--small-justify, space-between);\\n\\n  --text-center: var(--media-lte-sm) center;\\n  text-align: var(--text-center, initial);\\n\\n  line-height: 200%;\\n}\\n\\n.design-by {\\n  display: grid;\\n  --small-justify: var(--media-lte-sm) center;\\n  justify-content: var(--small-justify, end);\\n}</style>\\n\\n<div class=\\\"container\\\">\\n  <div class=\\\"info\\\">Svelte Summit is a volunteer effort.</div>\\n  <div class=\\\"design-by\\\">\\n    <span>\\n      Design by\\n      <a\\n        target=\\\"_blank\\\"\\n        rel=\\\"noreferrer\\\"\\n        href=\\\"https://twitter.com/mono_company\\\">\\n        @mono_company\\n      </a>\\n    </span>\\n    <span>\\n      Built by\\n      <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https://svelte.school\\\">\\n        Svelte School\\n      </a>\\n    </span>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,UAAU,eAAC,CAAC,AACV,KAAK,CAAE,KAAK,IAAI,CAAC,CAAC,CAAC,IAAI,CAAC,CACxB,iBAAiB,CAAE,yBAAyB,CAC5C,SAAS,CAAE,IAAI,iBAAiB,CAAC,uBAAuB,CAAC,CACzD,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,OAAO,CAAE,GAAG,CACZ,eAAe,CAAE,wCAAwC,CACzD,OAAO,CAAE,IAAI,eAAe,CAAC,qBAAqB,CAAC,CAEnD,OAAO,CAAE,IAAI,CACb,YAAY,CAAE,wBAAwB,CACtC,qBAAqB,CAAE,IAAI,YAAY,CAAC,UAAU,CAAC,CAEnD,eAAe,CAAE,0BAA0B,CAC3C,eAAe,CAAE,IAAI,eAAe,CAAC,cAAc,CAAC,CAEpD,aAAa,CAAE,0BAA0B,CACzC,UAAU,CAAE,IAAI,aAAa,CAAC,QAAQ,CAAC,CAEvC,WAAW,CAAE,IAAI,AACnB,CAAC,AAED,UAAU,eAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,0BAA0B,CAC3C,eAAe,CAAE,IAAI,eAAe,CAAC,IAAI,CAAC,AAC5C,CAAC\"}"
};

const Footer = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css$f);

	return `<div class="${"container svelte-1vhtiuj"}"><div class="${"info"}">Svelte Summit is a volunteer effort.</div>
  <div class="${"design-by svelte-1vhtiuj"}"><span>Design by
      <a target="${"_blank"}" rel="${"noreferrer"}" href="${"https://twitter.com/mono_company"}">@mono_company
      </a></span>
    <span>Built by
      <a target="${"_blank"}" rel="${"noreferrer"}" href="${"https://svelte.school"}">Svelte School
      </a></span></div></div>`;
});

/* src/routes/home/Home.svelte generated by Svelte v3.24.0 */

const Home = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { data } = $$props;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `${($$result.head += `${($$result.title = `<title>Svelte Summit 2020</title>`, "")}<meta charset="${"UTF-8"}" data-svelte="svelte-1few93s"><meta name="${"viewport"}" content="${"width=device-width, initial-scale=1.0"}" data-svelte="svelte-1few93s">${($$result.title = `<title>Svelte Summit is a FREE whole-day online event.</title>`, "")}<meta name="${"title"}" content="${"Svelte Summit is a FREE whole-day online event."}" data-svelte="svelte-1few93s"><meta name="${"description"}" content="${"Svelte Summit is an online JavaScript event focused on Svelte and its community taking place on October 18th 2020."}" data-svelte="svelte-1few93s"><meta property="${"og:type"}" content="${"website"}" data-svelte="svelte-1few93s"><meta property="${"og:url"}" content="${"https://sveltesummit.com/"}" data-svelte="svelte-1few93s"><meta property="${"og:title"}" content="${"Svelte Summit is a FREE whole-day online event."}" data-svelte="svelte-1few93s"><meta property="${"og:description"}" content="${"Svelte Summit is an online JavaScript event focused on Svelte and its community taking place on October 18th."}" data-svelte="svelte-1few93s"><meta property="${"og:image"}" content="${"https://sveltesummit.com/images/metatagimg.png"}" data-svelte="svelte-1few93s"><meta property="${"twitter:card"}" content="${"summary_large_image"}" data-svelte="svelte-1few93s"><meta property="${"twitter:url"}" content="${"https://sveltesummit.com/"}" data-svelte="svelte-1few93s"><meta property="${"twitter:title"}" content="${"Svelte Summit is a FREE whole-day online event."}" data-svelte="svelte-1few93s"><meta property="${"twitter:description"}" content="${"Svelte Summit is an online JavaScript event focused on Svelte and its community taking place on October 18th."}" data-svelte="svelte-1few93s"><meta property="${"twitter:image"}" content="${"https://sveltesummit.com/images/metatagimg.png"}" data-svelte="svelte-1few93s">`, "")}

${validate_component(Hero, "Hero").$$render($$result, {}, {}, {})}
${validate_component(Sponsors, "Sponsors").$$render($$result, {}, {}, {})}
${validate_component(Speakers, "Speakers").$$render($$result, { talks: data.markdown }, {}, {})}
${validate_component(FAQ, "FAQ").$$render($$result, {}, {}, {
		default: () => `${validate_component(Question, "Question").$$render($$result, { title: "What is this?" }, {}, {
			default: () => `Svelte Summit is an event dedicated to Svelte and everything that is
    happening in the community. You&#39;ll be able to tune in to a full day of talks
    and discussions all while chatting to other Svelthusiasts on the Discord
    server.
  `
		})}
  ${validate_component(Question, "Question").$$render($$result, { title: "When is it? What time?" }, {}, {
			default: () => `October 18th, 2020! The exact hour of the day is not set in stone but we
    will aim to do what we did last time and have talks all throughout the day.
    In practice this means that we will start around 12GMT and continue until
    we&#39;re done. This has the added benefit of making it possible for our
    speakers to be present when their talks are given so that they can answer
    questions.
  `
		})}
  ${validate_component(Question, "Question").$$render($$result, { title: "Will it be recorded" }, {}, {
			default: () => `Absolutely! You&#39;ll find it on the Svelte Society <a rel="${"noreferrer"}" target="${"_blank"}" href="${"https://www.youtube.com/channel/UCZSr5B0l07JXK2FIeWA0-jw"}">YouTube channel
    </a> once the event has been finished.
  `
		})}
  ${validate_component(Question, "Question").$$render($$result, { title: "How do I watch it?" }, {}, {
			default: () => `Once the day arrives, tune in to the Svelte Society YouTube channel and
    start watching. We&#39;ll also make sure to post a notice at the top of this
    page if you forget where to go.
  `
		})}
  ${validate_component(Question, "Question").$$render(
			$$result,
			{
				title: "Can you remind me when the date gets closer?"
			},
			{},
			{
				default: () => `Yes, <a rel="${"noreferrer"}" href="${"https://forms.gle/6PBKXng9jfrvxjhX8"}" target="${"_blank"}">enter
      your email here. </a>`
			}
		)}`
	})}
${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})}`;
});

module.exports = Home;
