'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/Hero/Info.svelte generated by Svelte v3.24.0 */

const css = {
	code: ".info.svelte-1gnpq5v{display:grid;grid-gap:12px;--columns-small:var(--media-lte-sm) 2fr 3fr;grid-template-columns:var(--columns-small, 1fr);--small-placement:var(--media-lte-sm) start end;place-items:var(--small-placement, start)}time.svelte-1gnpq5v{line-height:105%;--small:var(--media-lte-sm) 40px;display:grid;--small-placement:var(--media-lte-sm) end;place-items:var(--small-placement, center start);--small:var(--media-lte-sm) 50px;font-size:var(--small, 73px)}span.svelte-1gnpq5v{--align-text-mobile:var(--media-lte-sm) right;text-align:var(--align-text-mobile, initial)}.sub.svelte-1gnpq5v{--small:var(--media-lte-sm) 33px;font-size:var(--small, 40px);--small-line:var(--media-lte-sm) 100%;line-height:var(--small-line, 105%);display:grid;--small-placement:var(--media-lte-sm) left;text-align:var(--small-placement, left);--small-width:var(--media-lte-sm) 250px;max-width:var(--small-width, 300px)}",
	map: "{\"version\":3,\"file\":\"Info.svelte\",\"sources\":[\"Info.svelte\"],\"sourcesContent\":[\"<style>\\n.info {\\n  display: grid;\\n  grid-gap: 12px;\\n\\n  --columns-small: var(--media-lte-sm) 2fr 3fr;\\n  grid-template-columns: var(--columns-small, 1fr);\\n\\n  --small-placement: var(--media-lte-sm) start end;\\n  place-items: var(--small-placement, start);\\n}\\ntime {\\n  line-height: 105%;\\n  --small: var(--media-lte-sm) 40px;\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) end;\\n  place-items: var(--small-placement, center start);\\n  --small: var(--media-lte-sm) 50px;\\n  font-size: var(--small, 73px);\\n}\\nspan {\\n  --align-text-mobile: var(--media-lte-sm) right;\\n  text-align: var(--align-text-mobile, initial);\\n}\\n.sub {\\n  --small: var(--media-lte-sm) 33px;\\n  font-size: var(--small, 40px);\\n\\n  --small-line: var(--media-lte-sm) 100%;\\n  line-height: var(--small-line, 105%);\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) left;\\n  text-align: var(--small-placement, left);\\n\\n  --small-width: var(--media-lte-sm) 250px;\\n  max-width: var(--small-width, 300px);\\n}</style>\\n\\n<div class=\\\"info\\\">\\n  <time class=\\\"display\\\" datetime=\\\"2020-10-18\\\">\\n    <span>OCT 18</span>\\n    <span>2020</span>\\n  </time>\\n  <div class=\\\"sub display\\\">THE 2ND VIRTUAL CONFERENCE ABOUT SVELTE</div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,KAAK,eAAC,CAAC,AACL,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CAEd,eAAe,CAAE,2BAA2B,CAC5C,qBAAqB,CAAE,IAAI,eAAe,CAAC,IAAI,CAAC,CAEhD,iBAAiB,CAAE,6BAA6B,CAChD,WAAW,CAAE,IAAI,iBAAiB,CAAC,MAAM,CAAC,AAC5C,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,WAAW,CAAE,IAAI,CACjB,OAAO,CAAE,wBAAwB,CAEjC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,uBAAuB,CAC1C,WAAW,CAAE,IAAI,iBAAiB,CAAC,aAAa,CAAC,CACjD,OAAO,CAAE,wBAAwB,CACjC,SAAS,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC/B,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,mBAAmB,CAAE,yBAAyB,CAC9C,UAAU,CAAE,IAAI,mBAAmB,CAAC,QAAQ,CAAC,AAC/C,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,OAAO,CAAE,wBAAwB,CACjC,SAAS,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,CAE7B,YAAY,CAAE,wBAAwB,CACtC,WAAW,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CAEpC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,wBAAwB,CAC3C,UAAU,CAAE,IAAI,iBAAiB,CAAC,KAAK,CAAC,CAExC,aAAa,CAAE,yBAAyB,CACxC,SAAS,CAAE,IAAI,aAAa,CAAC,MAAM,CAAC,AACtC,CAAC\"}"
};

const Info = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css);

	return `<div class="${"info svelte-1gnpq5v"}"><time class="${"display svelte-1gnpq5v"}" datetime="${"2020-10-18"}"><span class="${"svelte-1gnpq5v"}">OCT 18</span>
    <span class="${"svelte-1gnpq5v"}">2020</span></time>
  <div class="${"sub display svelte-1gnpq5v"}">THE 2ND VIRTUAL CONFERENCE ABOUT SVELTE</div></div>`;
});

module.exports = Info;
