'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* src/components/Hero/Navigation.svelte generated by Svelte v3.26.0 */

const css = {
	code: ".navcontainer.svelte-fpzbx8{position:fixed;top:0;left:0;padding:25px 0 20px 0;width:100%;align-items:center;justify-content:center;background-color:rgba(0, 0, 0, 0.1);transition:background-color 0.3s ease;--small:var(--media-lte-sm) none;display:var(--small, flex)}.navcontainer.scrolled.svelte-fpzbx8{background-color:#162b2e}.big-nav.svelte-fpzbx8{color:#2a8290;font-size:19px;margin:0 24px;padding:4px 20px;text-decoration:none;display:inline-flex;transition:background-color 0.3s ease}.big-nav.svelte-fpzbx8:visited{color:#2a8290}.big-nav.svelte-fpzbx8:hover,.big-nav.svelte-fpzbx8:focus{background:rgba(255, 255, 255, 0.2)}a.scrolled.svelte-fpzbx8{color:white}a.scrolled.svelte-fpzbx8:visited{color:white}.hamburger.svelte-fpzbx8{position:absolute;padding:30px;top:6px;right:6px;--small:var(--media-lte-sm) initial;display:var(--small, none)}.twitter.svelte-fpzbx8{height:16px;place-self:center}span.svelte-fpzbx8{display:grid;grid-gap:8px;grid-template-columns:auto auto;justify-items:center}.container.svelte-fpzbx8{background:#17353a;position:fixed;top:0;left:0;right:0;bottom:0;width:100%}ul.svelte-fpzbx8{padding-top:100px;padding-bottom:100px;display:grid;grid-gap:40px;list-style:none}li.svelte-fpzbx8{text-transform:uppercase;font-family:Anton;font-size:48px;line-height:120%}.small-nav.svelte-fpzbx8:hover{color:white;opacity:1}.small-nav.svelte-fpzbx8{color:var(--sky-blue);opacity:0.6;text-decoration:none;letter-spacing:0.6px}button.svelte-fpzbx8{background:transparent;border:none;position:absolute;top:6px;right:6px}.close.svelte-fpzbx8{padding:30px}",
	map: "{\"version\":3,\"file\":\"Navigation.svelte\",\"sources\":[\"Navigation.svelte\"],\"sourcesContent\":[\"<script>\\nlet y;\\n$: scrolled = y > 100;\\nexport let menu;\\nlet menuOpen = false;\\n</script>\\n\\n<style>\\n.navcontainer {\\n  position: fixed;\\n  top: 0;\\n  left: 0;\\n  padding: 25px 0 20px 0;\\n  width: 100%;\\n  align-items: center;\\n  justify-content: center;\\n  background-color: rgba(0, 0, 0, 0.1);\\n  transition: background-color 0.3s ease;\\n  --small: var(--media-lte-sm) none;\\n  display: var(--small, flex);\\n}\\n.navcontainer.scrolled {\\n  background-color: #162b2e;\\n}\\n\\n.big-nav {\\n  color: #2a8290;\\n  font-size: 19px;\\n  margin: 0 24px;\\n  padding: 4px 20px;\\n  text-decoration: none;\\n  display: inline-flex;\\n\\n  transition: background-color 0.3s ease;\\n}\\n\\n.big-nav:visited {\\n  color: #2a8290;\\n}\\n\\n.big-nav:hover,\\n.big-nav:focus {\\n  background: rgba(255, 255, 255, 0.2);\\n}\\n\\na.scrolled {\\n  color: white;\\n}\\n\\na.scrolled:visited {\\n  color: white;\\n}\\n\\n.hamburger {\\n  position: absolute;\\n  padding: 30px;\\n  top: 6px;\\n  right: 6px;\\n\\n  --small: var(--media-lte-sm) initial;\\n  display: var(--small, none);\\n}\\n.twitter {\\n  height: 16px;\\n  place-self: center;\\n}\\nspan {\\n  display: grid;\\n  grid-gap: 8px;\\n  grid-template-columns: auto auto;\\n  justify-items: center;\\n}\\n.container {\\n  background: #17353a;\\n  position: fixed;\\n  top: 0;\\n  left: 0;\\n  right: 0;\\n  bottom: 0;\\n  width: 100%;\\n}\\nul {\\n  padding-top: 100px;\\n  padding-bottom: 100px;\\n  display: grid;\\n  grid-gap: 40px;\\n  list-style: none;\\n}\\nli {\\n  text-transform: uppercase;\\n  font-family: Anton;\\n  font-size: 48px;\\n  line-height: 120%;\\n}\\n.small-nav:hover {\\n  color: white;\\n  opacity: 1;\\n}\\n.small-nav {\\n  color: var(--sky-blue);\\n  opacity: 0.6;\\n  text-decoration: none;\\n  letter-spacing: 0.6px;\\n}\\nbutton {\\n  background: transparent;\\n  border: none;\\n  position: absolute;\\n  top: 6px;\\n  right: 6px;\\n}\\n.close {\\n  padding: 30px;\\n}</style>\\n\\n<svelte:window bind:scrollY={y} />\\n<div class=\\\"navcontainer\\\" class:scrolled>\\n  <nav>\\n    {#each menu as { url, name }}\\n      <a class=\\\"big-nav\\\" href={url} class:scrolled> {name} </a>\\n    {/each}\\n\\n    <a\\n      class=\\\"big-nav\\\"\\n      rel=\\\"noreferrer\\\"\\n      href=\\\"https://forms.gle/6PBKXng9jfrvxjhX8\\\"\\n      target=\\\"_blank\\\"\\n      class:scrolled>\\n      Sign Up\\n    </a>\\n\\n    <a\\n      class=\\\"big-nav\\\"\\n      rel=\\\"noreferrer\\\"\\n      target=\\\"_blank\\\"\\n      href=\\\"https://twitter.com/sveltesociety\\\"\\n      class:scrolled>\\n      <span>\\n        <img class=\\\"twitter\\\" src=\\\"/images/twitter.svg\\\" alt=\\\"\\\" /> Twitter\\n      </span>\\n    </a>\\n  </nav>\\n</div>\\n<div class=\\\"hamburger\\\" on:click={() => (menuOpen = true)}>\\n  <img src=\\\"/images/burger.svg\\\" alt=\\\"\\\" />\\n</div>\\n\\n{#if menuOpen}\\n  <div class=\\\"container\\\">\\n    <ul>\\n      {#each menu as { name, url }}\\n        <li>\\n          <a\\n            class=\\\"small-nav\\\"\\n            on:click={() => (menuOpen = false)}\\n            href=\\\"/{url}\\\">{name}</a>\\n        </li>\\n      {/each}\\n      <li>\\n        <a\\n          class=\\\"small-nav\\\"\\n          href=\\\"https://forms.gle/6PBKXng9jfrvxjhX8\\\"\\n          rel=\\\"noreferrer\\\"\\n          target=\\\"_blank\\\">\\n          Sign up\\n        </a>\\n      </li>\\n      <li>\\n        <a\\n          class=\\\"small-nav\\\"\\n          target=\\\"_blank\\\"\\n          rel=\\\"noreferrer\\\"\\n          href=\\\"https://twitter.com/sveltesociety\\\">Twitter</a>\\n      </li>\\n    </ul>\\n    <button on:click={() => (menuOpen = false)}>\\n      <img class=\\\"close\\\" src=\\\"images/close.svg\\\" alt=\\\"\\\" />\\n    </button>\\n  </div>\\n{/if}\\n\"],\"names\":[],\"mappings\":\"AAQA,aAAa,cAAC,CAAC,AACb,QAAQ,CAAE,KAAK,CACf,GAAG,CAAE,CAAC,CACN,IAAI,CAAE,CAAC,CACP,OAAO,CAAE,IAAI,CAAC,CAAC,CAAC,IAAI,CAAC,CAAC,CACtB,KAAK,CAAE,IAAI,CACX,WAAW,CAAE,MAAM,CACnB,eAAe,CAAE,MAAM,CACvB,gBAAgB,CAAE,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CACpC,UAAU,CAAE,gBAAgB,CAAC,IAAI,CAAC,IAAI,CACtC,OAAO,CAAE,wBAAwB,CACjC,OAAO,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC7B,CAAC,AACD,aAAa,SAAS,cAAC,CAAC,AACtB,gBAAgB,CAAE,OAAO,AAC3B,CAAC,AAED,QAAQ,cAAC,CAAC,AACR,KAAK,CAAE,OAAO,CACd,SAAS,CAAE,IAAI,CACf,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,OAAO,CAAE,GAAG,CAAC,IAAI,CACjB,eAAe,CAAE,IAAI,CACrB,OAAO,CAAE,WAAW,CAEpB,UAAU,CAAE,gBAAgB,CAAC,IAAI,CAAC,IAAI,AACxC,CAAC,AAED,sBAAQ,QAAQ,AAAC,CAAC,AAChB,KAAK,CAAE,OAAO,AAChB,CAAC,AAED,sBAAQ,MAAM,CACd,sBAAQ,MAAM,AAAC,CAAC,AACd,UAAU,CAAE,KAAK,GAAG,CAAC,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,AACtC,CAAC,AAED,CAAC,SAAS,cAAC,CAAC,AACV,KAAK,CAAE,KAAK,AACd,CAAC,AAED,CAAC,uBAAS,QAAQ,AAAC,CAAC,AAClB,KAAK,CAAE,KAAK,AACd,CAAC,AAED,UAAU,cAAC,CAAC,AACV,QAAQ,CAAE,QAAQ,CAClB,OAAO,CAAE,IAAI,CACb,GAAG,CAAE,GAAG,CACR,KAAK,CAAE,GAAG,CAEV,OAAO,CAAE,2BAA2B,CACpC,OAAO,CAAE,IAAI,OAAO,CAAC,KAAK,CAAC,AAC7B,CAAC,AACD,QAAQ,cAAC,CAAC,AACR,MAAM,CAAE,IAAI,CACZ,UAAU,CAAE,MAAM,AACpB,CAAC,AACD,IAAI,cAAC,CAAC,AACJ,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,GAAG,CACb,qBAAqB,CAAE,IAAI,CAAC,IAAI,CAChC,aAAa,CAAE,MAAM,AACvB,CAAC,AACD,UAAU,cAAC,CAAC,AACV,UAAU,CAAE,OAAO,CACnB,QAAQ,CAAE,KAAK,CACf,GAAG,CAAE,CAAC,CACN,IAAI,CAAE,CAAC,CACP,KAAK,CAAE,CAAC,CACR,MAAM,CAAE,CAAC,CACT,KAAK,CAAE,IAAI,AACb,CAAC,AACD,EAAE,cAAC,CAAC,AACF,WAAW,CAAE,KAAK,CAClB,cAAc,CAAE,KAAK,CACrB,OAAO,CAAE,IAAI,CACb,QAAQ,CAAE,IAAI,CACd,UAAU,CAAE,IAAI,AAClB,CAAC,AACD,EAAE,cAAC,CAAC,AACF,cAAc,CAAE,SAAS,CACzB,WAAW,CAAE,KAAK,CAClB,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,IAAI,AACnB,CAAC,AACD,wBAAU,MAAM,AAAC,CAAC,AAChB,KAAK,CAAE,KAAK,CACZ,OAAO,CAAE,CAAC,AACZ,CAAC,AACD,UAAU,cAAC,CAAC,AACV,KAAK,CAAE,IAAI,UAAU,CAAC,CACtB,OAAO,CAAE,GAAG,CACZ,eAAe,CAAE,IAAI,CACrB,cAAc,CAAE,KAAK,AACvB,CAAC,AACD,MAAM,cAAC,CAAC,AACN,UAAU,CAAE,WAAW,CACvB,MAAM,CAAE,IAAI,CACZ,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,GAAG,CACR,KAAK,CAAE,GAAG,AACZ,CAAC,AACD,MAAM,cAAC,CAAC,AACN,OAAO,CAAE,IAAI,AACf,CAAC\"}"
};

const Navigation = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let y;
	let { menu } = $$props;
	if ($$props.menu === void 0 && $$bindings.menu && menu !== void 0) $$bindings.menu(menu);
	$$result.css.add(css);
	let scrolled;
	scrolled = y > 100;

	return `
<div class="${["navcontainer svelte-fpzbx8", scrolled ? "scrolled" : ""].join(" ").trim()}"><nav>${each(menu, ({ url, name }) => `<a class="${["big-nav svelte-fpzbx8", scrolled ? "scrolled" : ""].join(" ").trim()}"${add_attribute("href", url, 0)}>${escape(name)} </a>`)}

    <a class="${["big-nav svelte-fpzbx8", scrolled ? "scrolled" : ""].join(" ").trim()}" rel="${"noreferrer"}" href="${"https://forms.gle/6PBKXng9jfrvxjhX8"}" target="${"_blank"}">Sign Up
    </a>

    <a class="${["big-nav svelte-fpzbx8", scrolled ? "scrolled" : ""].join(" ").trim()}" rel="${"noreferrer"}" target="${"_blank"}" href="${"https://twitter.com/sveltesociety"}"><span class="${"svelte-fpzbx8"}"><img class="${"twitter svelte-fpzbx8"}" src="${"/images/twitter.svg"}" alt="${""}"> Twitter
      </span></a></nav></div>
<div class="${"hamburger svelte-fpzbx8"}"><img src="${"/images/burger.svg"}" alt="${""}"></div>

${ ``}`;
});

module.exports = Navigation;
