'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/Sections/Sponsors.svelte generated by Svelte v3.26.0 */

const css = {
	code: ".background.svelte-12180b.svelte-12180b{--small-padding:var(--media-lte-sm) 50px 0;padding:var(--small-padding, 200px 40px 50px 40px);background:#2b636c;background-image:url(/images/lake.svg);background-position:top;background-repeat:no-repeat;--mobile-backgrounds:var(--media-lte-sm) auto 130px;background-size:var(--mobile-backgrounds, auto 150px)}.container.svelte-12180b.svelte-12180b{display:grid;--small-grid:var(--media-lte-sm) 0;grid-gap:var(--small-grid, 30px);max-width:var(--container-width)}h2.svelte-12180b.svelte-12180b{--small-font:var(--media-lte-sm) 34px;font-size:var(--small-font, 60px);font-family:\"Anton\";line-height:150%;text-align:center}.sponsors.svelte-12180b.svelte-12180b{--small-margin:var(--media-lte-sm) 0 15px;margin:var(--small-margin, initial);display:grid;justify-content:center;grid-gap:43px}.sponsors+.sponsors.svelte-12180b.svelte-12180b{--small-top:var(--media-lte-sm) 40px;margin-top:var(--small-top, 0)}.gold.svelte-12180b.svelte-12180b{grid-template-columns:repeat(auto-fit, minmax(300px, 330fr))}.silver.svelte-12180b.svelte-12180b{grid-template-columns:repeat(auto-fit, minmax(150px, 240px))}.sponsor.svelte-12180b.svelte-12180b{display:grid;justify-content:center;align-items:center;background:#1c464d;padding:30px 50px}.silver.sponsors.svelte-12180b .sponsor.svelte-12180b{padding:20px 40px}.gold.svelte-12180b img.svelte-12180b{height:66px;max-height:66px}.silver.svelte-12180b img.svelte-12180b{height:50px;max-height:50px;max-width:100%;-o-object-fit:contain;object-fit:contain}.info.svelte-12180b.svelte-12180b{min-width:0;color:#e4eef0;opacity:50%;margin:0 auto;margin-top:40px;max-width:575px;text-align:center}[data-tooltip].svelte-12180b.svelte-12180b{position:relative}[data-tooltip].svelte-12180b.svelte-12180b:before,[data-tooltip].svelte-12180b.svelte-12180b:after{position:absolute;visibility:hidden;opacity:0;transition:opacity 0.2s ease-in-out, visibility 0.2s ease-in-out,\n    transform 0.2s cubic-bezier(0.71, 1.7, 0.77, 1.24);transform:translate3d(0, 0, 0);pointer-events:none}[data-tooltip].svelte-12180b.svelte-12180b:hover:before,[data-tooltip].svelte-12180b.svelte-12180b:hover:after,[data-tooltip].svelte-12180b.svelte-12180b:focus:before,[data-tooltip].svelte-12180b.svelte-12180b:focus:after{visibility:visible;opacity:1}[data-tooltip].svelte-12180b.svelte-12180b:after{z-index:1000;padding:8px;width:260px;background-color:#000;background-color:hsla(0, 0%, 20%, 0.9);color:#fff;font-weight:normal;content:attr(data-tooltip);font-size:14px;line-height:1.2}[data-tooltip].svelte-12180b.svelte-12180b:before,[data-tooltip].svelte-12180b.svelte-12180b:after{top:100%;--small-adjust:var(--media-lte-sm) calc(50% - 138px);left:var(--small-adjust, calc(70% - 138px))}",
	map: "{\"version\":3,\"file\":\"Sponsors.svelte\",\"sources\":[\"Sponsors.svelte\"],\"sourcesContent\":[\"<style>\\n.background {\\n  --small-padding: var(--media-lte-sm) 50px 0;\\n  padding: var(--small-padding, 200px 40px 50px 40px);\\n\\n  background: #2b636c;\\n  background-image: url(/images/lake.svg);\\n  background-position: top;\\n  background-repeat: no-repeat;\\n\\n  --mobile-backgrounds: var(--media-lte-sm) auto 130px;\\n  background-size: var(--mobile-backgrounds, auto 150px);\\n}\\n.container {\\n  display: grid;\\n  --small-grid: var(--media-lte-sm) 0;\\n  grid-gap: var(--small-grid, 30px);\\n  max-width: var(--container-width);\\n\\n  /* --small-margin: var(--media-lte-sm) 0px 20px -50px 20px;\\n  margin: var(--small-margin, -120px auto 70px auto);\\n\\n  --small-padding: var(--media-lte-sm) 50px 0;\\n  padding: var(--small-padding, initial); */\\n}\\nh2 {\\n  --small-font: var(--media-lte-sm) 34px;\\n  font-size: var(--small-font, 60px);\\n  font-family: \\\"Anton\\\";\\n  line-height: 150%;\\n  text-align: center;\\n}\\n.sponsors {\\n  --small-margin: var(--media-lte-sm) 0 15px;\\n  margin: var(--small-margin, initial);\\n  display: grid;\\n  justify-content: center;\\n  grid-gap: 43px;\\n}\\n.sponsors + .sponsors {\\n  --small-top: var(--media-lte-sm) 40px;\\n  margin-top: var(--small-top, 0);\\n}\\n.gold {\\n  grid-template-columns: repeat(auto-fit, minmax(300px, 330fr));\\n}\\n.silver {\\n  grid-template-columns: repeat(auto-fit, minmax(150px, 240px));\\n}\\n.sponsor {\\n  display: grid;\\n  justify-content: center;\\n  align-items: center;\\n  background: #1c464d;\\n  padding: 30px 50px;\\n}\\n\\n.silver.sponsors .sponsor {\\n  padding: 20px 40px;\\n}\\n\\n.gold img {\\n  height: 66px;\\n  max-height: 66px;\\n}\\n\\n.silver img {\\n  height: 50px;\\n  max-height: 50px;\\n  max-width: 100%;\\n  -o-object-fit: contain;\\n     object-fit: contain;\\n}\\n.info {\\n  min-width: 0;\\n  color: #e4eef0;\\n  opacity: 50%;\\n  margin: 0 auto;\\n  margin-top: 40px;\\n  max-width: 575px;\\n  text-align: center;\\n}\\n\\n[data-tooltip] {\\n  position: relative;\\n}\\n\\n[data-tooltip]:before,\\n[data-tooltip]:after {\\n  position: absolute;\\n  visibility: hidden;\\n  opacity: 0;\\n  transition: opacity 0.2s ease-in-out, visibility 0.2s ease-in-out,\\n    transform 0.2s cubic-bezier(0.71, 1.7, 0.77, 1.24);\\n  transform: translate3d(0, 0, 0);\\n  pointer-events: none;\\n}\\n\\n[data-tooltip]:hover:before,\\n[data-tooltip]:hover:after,\\n[data-tooltip]:focus:before,\\n[data-tooltip]:focus:after {\\n  visibility: visible;\\n  opacity: 1;\\n}\\n\\n[data-tooltip]:after {\\n  z-index: 1000;\\n  padding: 8px;\\n  width: 260px;\\n  background-color: #000;\\n  background-color: hsla(0, 0%, 20%, 0.9);\\n  color: #fff;\\n  font-weight: normal;\\n  content: attr(data-tooltip);\\n  font-size: 14px;\\n  line-height: 1.2;\\n}\\n\\n[data-tooltip]:before,\\n[data-tooltip]:after {\\n  top: 100%;\\n\\n  --small-adjust: var(--media-lte-sm) calc(50% - 138px);\\n  left: var(--small-adjust, calc(70% - 138px));\\n}</style>\\n\\n<div class=\\\"background\\\" id=\\\"sponsors\\\">\\n  <div class=\\\"container\\\">\\n    <h2>SPONSORED BY</h2>\\n    <div class=\\\"gold sponsors\\\">\\n      <a\\n        href=\\\"https://aws.amazon.com/amplify/\\\"\\n        rel=\\\"noopener noreferrer\\\"\\n        target=\\\"_blank\\\"\\n        class=\\\"sponsor\\\"\\n        data-tooltip=\\\"AWS Amplify – The fastest, easiest way to develop mobile and web apps that scale\\\">\\n        <img src=\\\"/images/sponsors/aws.svg\\\" alt=\\\"\\\" />\\n      </a>\\n      <a\\n        href=\\\"https://www.coderight.se\\\"\\n        rel=\\\"noopener noreferrer\\\"\\n        target=\\\"_blank\\\"\\n        class=\\\"sponsor\\\">\\n        <img src=\\\"/images/sponsors/b3coderight.svg\\\" alt=\\\"\\\" />\\n      </a>\\n    </div>\\n    <div class=\\\"silver sponsors\\\">\\n      <a\\n        href=\\\"https://oasisdigital.com\\\"\\n        rel=\\\"noopener noreferrer\\\"\\n        target=\\\"_blank\\\"\\n        class=\\\"sponsor\\\"\\n        data-tooltip=\\\"Oasis Digital delivers advanced software product development and training services, focused on web technology and full stack solutions.\\\">\\n        <img src=\\\"/images/sponsors/oasis.svg\\\" alt=\\\"\\\" />\\n      </a>\\n      <a\\n        href=\\\"https://www.humancontent.nl\\\"\\n        rel=\\\"noopener noreferrer\\\"\\n        target=\\\"_blank\\\"\\n        class=\\\"sponsor\\\"\\n        data-tooltip=\\\"Whether it is a website, a business application or a mobile app; we take care of the entire process, from the first consultation to an end product with maximum added value for the customer and end users.\\\">\\n        <img src=\\\"/images/sponsors/humancontent.svg\\\" alt=\\\"\\\" />\\n      </a>\\n    </div>\\n    <p class=\\\"info\\\">\\n      More sponsors welcome! Any financial backing will be used to support the\\n      event and further development of Svelte itself. <a\\n        href=\\\"mailto:sponsors@sveltesociety.dev\\\">Get in touch</a>.\\n    </p>\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AACA,WAAW,4BAAC,CAAC,AACX,eAAe,CAAE,0BAA0B,CAC3C,OAAO,CAAE,IAAI,eAAe,CAAC,qBAAqB,CAAC,CAEnD,UAAU,CAAE,OAAO,CACnB,gBAAgB,CAAE,IAAI,gBAAgB,CAAC,CACvC,mBAAmB,CAAE,GAAG,CACxB,iBAAiB,CAAE,SAAS,CAE5B,oBAAoB,CAAE,8BAA8B,CACpD,eAAe,CAAE,IAAI,oBAAoB,CAAC,WAAW,CAAC,AACxD,CAAC,AACD,UAAU,4BAAC,CAAC,AACV,OAAO,CAAE,IAAI,CACb,YAAY,CAAE,qBAAqB,CACnC,QAAQ,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CACjC,SAAS,CAAE,IAAI,iBAAiB,CAAC,AAOnC,CAAC,AACD,EAAE,4BAAC,CAAC,AACF,YAAY,CAAE,wBAAwB,CACtC,SAAS,CAAE,IAAI,YAAY,CAAC,KAAK,CAAC,CAClC,WAAW,CAAE,OAAO,CACpB,WAAW,CAAE,IAAI,CACjB,UAAU,CAAE,MAAM,AACpB,CAAC,AACD,SAAS,4BAAC,CAAC,AACT,cAAc,CAAE,0BAA0B,CAC1C,MAAM,CAAE,IAAI,cAAc,CAAC,QAAQ,CAAC,CACpC,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,MAAM,CACvB,QAAQ,CAAE,IAAI,AAChB,CAAC,AACD,SAAS,CAAG,SAAS,4BAAC,CAAC,AACrB,WAAW,CAAE,wBAAwB,CACrC,UAAU,CAAE,IAAI,WAAW,CAAC,EAAE,CAAC,AACjC,CAAC,AACD,KAAK,4BAAC,CAAC,AACL,qBAAqB,CAAE,OAAO,QAAQ,CAAC,CAAC,OAAO,KAAK,CAAC,CAAC,KAAK,CAAC,CAAC,AAC/D,CAAC,AACD,OAAO,4BAAC,CAAC,AACP,qBAAqB,CAAE,OAAO,QAAQ,CAAC,CAAC,OAAO,KAAK,CAAC,CAAC,KAAK,CAAC,CAAC,AAC/D,CAAC,AACD,QAAQ,4BAAC,CAAC,AACR,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,MAAM,CACnB,UAAU,CAAE,OAAO,CACnB,OAAO,CAAE,IAAI,CAAC,IAAI,AACpB,CAAC,AAED,OAAO,uBAAS,CAAC,QAAQ,cAAC,CAAC,AACzB,OAAO,CAAE,IAAI,CAAC,IAAI,AACpB,CAAC,AAED,mBAAK,CAAC,GAAG,cAAC,CAAC,AACT,MAAM,CAAE,IAAI,CACZ,UAAU,CAAE,IAAI,AAClB,CAAC,AAED,qBAAO,CAAC,GAAG,cAAC,CAAC,AACX,MAAM,CAAE,IAAI,CACZ,UAAU,CAAE,IAAI,CAChB,SAAS,CAAE,IAAI,CACf,aAAa,CAAE,OAAO,CACnB,UAAU,CAAE,OAAO,AACxB,CAAC,AACD,KAAK,4BAAC,CAAC,AACL,SAAS,CAAE,CAAC,CACZ,KAAK,CAAE,OAAO,CACd,OAAO,CAAE,GAAG,CACZ,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,UAAU,CAAE,IAAI,CAChB,SAAS,CAAE,KAAK,CAChB,UAAU,CAAE,MAAM,AACpB,CAAC,AAED,CAAC,YAAY,CAAC,4BAAC,CAAC,AACd,QAAQ,CAAE,QAAQ,AACpB,CAAC,AAED,CAAC,YAAY,6BAAC,OAAO,CACrB,CAAC,YAAY,6BAAC,MAAM,AAAC,CAAC,AACpB,QAAQ,CAAE,QAAQ,CAClB,UAAU,CAAE,MAAM,CAClB,OAAO,CAAE,CAAC,CACV,UAAU,CAAE,OAAO,CAAC,IAAI,CAAC,WAAW,CAAC,CAAC,UAAU,CAAC,IAAI,CAAC,WAAW,CAAC;IAChE,SAAS,CAAC,IAAI,CAAC,aAAa,IAAI,CAAC,CAAC,GAAG,CAAC,CAAC,IAAI,CAAC,CAAC,IAAI,CAAC,CACpD,SAAS,CAAE,YAAY,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAC/B,cAAc,CAAE,IAAI,AACtB,CAAC,AAED,CAAC,YAAY,6BAAC,MAAM,OAAO,CAC3B,CAAC,YAAY,6BAAC,MAAM,MAAM,CAC1B,CAAC,YAAY,6BAAC,MAAM,OAAO,CAC3B,CAAC,YAAY,6BAAC,MAAM,MAAM,AAAC,CAAC,AAC1B,UAAU,CAAE,OAAO,CACnB,OAAO,CAAE,CAAC,AACZ,CAAC,AAED,CAAC,YAAY,6BAAC,MAAM,AAAC,CAAC,AACpB,OAAO,CAAE,IAAI,CACb,OAAO,CAAE,GAAG,CACZ,KAAK,CAAE,KAAK,CACZ,gBAAgB,CAAE,IAAI,CACtB,gBAAgB,CAAE,KAAK,CAAC,CAAC,CAAC,EAAE,CAAC,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,CACvC,KAAK,CAAE,IAAI,CACX,WAAW,CAAE,MAAM,CACnB,OAAO,CAAE,KAAK,YAAY,CAAC,CAC3B,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,GAAG,AAClB,CAAC,AAED,CAAC,YAAY,6BAAC,OAAO,CACrB,CAAC,YAAY,6BAAC,MAAM,AAAC,CAAC,AACpB,GAAG,CAAE,IAAI,CAET,cAAc,CAAE,qCAAqC,CACrD,IAAI,CAAE,IAAI,cAAc,CAAC,kBAAkB,CAAC,AAC9C,CAAC\"}"
};

const Sponsors = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `<div class="${"background svelte-12180b"}" id="${"sponsors"}"><div class="${"container svelte-12180b"}"><h2 class="${"svelte-12180b"}">SPONSORED BY</h2>
    <div class="${"gold sponsors svelte-12180b"}"><a href="${"https://aws.amazon.com/amplify/"}" rel="${"noopener noreferrer"}" target="${"_blank"}" class="${"sponsor svelte-12180b"}" data-tooltip="${"AWS Amplify – The fastest, easiest way to develop mobile and web apps that scale"}"><img src="${"/images/sponsors/aws.svg"}" alt="${""}" class="${"svelte-12180b"}"></a>
      <a href="${"https://www.coderight.se"}" rel="${"noopener noreferrer"}" target="${"_blank"}" class="${"sponsor svelte-12180b"}"><img src="${"/images/sponsors/b3coderight.svg"}" alt="${""}" class="${"svelte-12180b"}"></a></div>
    <div class="${"silver sponsors svelte-12180b"}"><a href="${"https://oasisdigital.com"}" rel="${"noopener noreferrer"}" target="${"_blank"}" class="${"sponsor svelte-12180b"}" data-tooltip="${"Oasis Digital delivers advanced software product development and training services, focused on web technology and full stack solutions."}"><img src="${"/images/sponsors/oasis.svg"}" alt="${""}" class="${"svelte-12180b"}"></a>
      <a href="${"https://www.humancontent.nl"}" rel="${"noopener noreferrer"}" target="${"_blank"}" class="${"sponsor svelte-12180b"}" data-tooltip="${"Whether it is a website, a business application or a mobile app; we take care of the entire process, from the first consultation to an end product with maximum added value for the customer and end users."}"><img src="${"/images/sponsors/humancontent.svg"}" alt="${""}" class="${"svelte-12180b"}"></a></div>
    <p class="${"info svelte-12180b"}">More sponsors welcome! Any financial backing will be used to support the
      event and further development of Svelte itself. <a href="${"mailto:sponsors@sveltesociety.dev"}">Get in touch</a>.
    </p></div></div>`;
});

module.exports = Sponsors;
