'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* src/components/Hero/Title.svelte generated by Svelte v3.24.0 */

const css = {
	code: "h1.svelte-16fjkkh{-webkit-margin-before:0;margin-block-start:0;-webkit-margin-after:0;margin-block-end:0;--small-margin:var(--media-lte-sm) 0px;margin-top:var(--small-margin, 155px);display:grid;--small-placement:var(--media-lte-sm) center;place-items:var(--small-placement, center end)}.leading.svelte-16fjkkh{color:var(--background-darkest)}.lagging.svelte-16fjkkh{color:var(--background)}",
	map: "{\"version\":3,\"file\":\"Title.svelte\",\"sources\":[\"Title.svelte\"],\"sourcesContent\":[\"<style>\\nh1 {\\n  -webkit-margin-before: 0;\\n          margin-block-start: 0;\\n  -webkit-margin-after: 0;\\n          margin-block-end: 0;\\n  --small-margin: var(--media-lte-sm) 0px;\\n  margin-top: var(--small-margin, 155px);\\n\\n  display: grid;\\n  --small-placement: var(--media-lte-sm) center;\\n  place-items: var(--small-placement, center end);\\n}\\n.leading {\\n  color: var(--background-darkest);\\n}\\n.lagging {\\n  color: var(--background);\\n}</style>\\n\\n<h1 class=\\\"display\\\">\\n  <span class=\\\"leading\\\">SVELTE</span>\\n  <span class=\\\"lagging\\\">SUMMIT</span>\\n</h1>\\n\"],\"names\":[],\"mappings\":\"AACA,EAAE,eAAC,CAAC,AACF,qBAAqB,CAAE,CAAC,CAChB,kBAAkB,CAAE,CAAC,CAC7B,oBAAoB,CAAE,CAAC,CACf,gBAAgB,CAAE,CAAC,CAC3B,cAAc,CAAE,uBAAuB,CACvC,UAAU,CAAE,IAAI,cAAc,CAAC,MAAM,CAAC,CAEtC,OAAO,CAAE,IAAI,CACb,iBAAiB,CAAE,0BAA0B,CAC7C,WAAW,CAAE,IAAI,iBAAiB,CAAC,WAAW,CAAC,AACjD,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,KAAK,CAAE,IAAI,oBAAoB,CAAC,AAClC,CAAC,AACD,QAAQ,eAAC,CAAC,AACR,KAAK,CAAE,IAAI,YAAY,CAAC,AAC1B,CAAC\"}"
};

const Title = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css);

	return `<h1 class="${"display svelte-16fjkkh"}"><span class="${"leading svelte-16fjkkh"}">SVELTE</span>
  <span class="${"lagging svelte-16fjkkh"}">SUMMIT</span></h1>`;
});

module.exports = Title;
